import type { Locale } from "@/lib/i18n/config";

type Pair = Record<Locale, string>;
export type MuscleView = "front" | "back";
export type MuscleSummary = {
  id: string; view: MuscleView; region: string; name: Pair; scientific: string; summary: Pair;
  function: Pair; benefit: Pair; training: Pair; mistake: Pair; exercises: Pair;
};

const pair = (en: string, mk: string): Pair => ({ en, mk });
const commonBenefit = pair("Balanced training can improve joint control, everyday strength, and confidence in related movement patterns.", "Урамнотежениот тренинг може да ја подобри контролата на зглобовите, секојдневната сила и сигурноста во сродните движења.");
const commonMistake = pair("Adding load before the movement is controlled through a comfortable range.", "Додавање тежина пред движењето да биде контролирано во удобен опсег.");

export const muscles: MuscleSummary[] = [
  {id:"pectorals",view:"front",region:"chest",name:pair("Pectorals","Градни мускули"),scientific:"Pectoralis major",summary:pair("The broad chest muscles used in pressing and bringing the arm across the body.","Широките градни мускули што учествуваат во потиснување и носење на раката кон телото."),function:pair("Moves the upper arm across the body and assists shoulder flexion and rotation.","Ја носи надлактицата кон телото и помага во свиткување и ротација на рамото."),benefit:commonBenefit,training:pair("Use push-ups and presses with a controlled lowering phase and comfortable shoulder position.","Користи склекови и потисоци со контролирано спуштање и удобна положба на рамото."),mistake:commonMistake,exercises:pair("Push-up · Dumbbell press · Cable press","Склек · Потисок со тегови · Кабелски потисок")},
  {id:"deltoids",view:"front",region:"shoulders",name:pair("Deltoids","Делтоидни мускули"),scientific:"Deltoideus",summary:pair("The rounded shoulder muscles that raise and rotate the arm.","Заоблените мускули на рамото што ја подигнуваат и ротираат раката."),function:pair("Raises the arm in several directions and helps center the shoulder joint.","Ја подигнува раката во повеќе насоки и помага во центрирање на рамениот зглоб."),benefit:commonBenefit,training:pair("Combine overhead presses with controlled lateral and rear-delt raises.","Комбинирај потисок над глава со контролирани странични и задни подигнувања."),mistake:commonMistake,exercises:pair("Overhead press · Lateral raise · Rear-delt raise","Потисок над глава · Странично подигнување · Задно подигнување")},
  {id:"biceps",view:"front",region:"arms",name:pair("Biceps","Бицепс"),scientific:"Biceps brachii",summary:pair("The front upper-arm muscles involved in bending the elbow and turning the palm.","Предните мускули на надлактицата што го свиткуваат лактот и ја вртат дланката."),function:pair("Flexes the elbow and turns the palm upward during pulling and carrying.","Го свиткува лактот и ја врти дланката нагоре при влечење и носење."),benefit:commonBenefit,training:pair("Use rows and curls while keeping the upper arm stable and wrist neutral.","Користи веслања и прегиби со стабилна надлактица и неутрален зглоб."),mistake:commonMistake,exercises:pair("Row · Curl · Chin-up","Веслање · Прегиб · Згиб")},
  {id:"abdominals",view:"front",region:"core",name:pair("Abdominals","Стомачни мускули"),scientific:"Rectus abdominis",summary:pair("The front trunk muscles that help control the relationship between ribs and pelvis.","Предните мускули на трупот што ја контролираат положбата на ребрата и карлицата."),function:pair("Flexes the trunk and resists excessive spinal extension.","Го свиткува трупот и се спротивставува на прекумерно истегнување на ’рбетот."),benefit:commonBenefit,training:pair("Use planks and controlled curl patterns while continuing to breathe.","Користи планк и контролирани свиткувања со непрекинато дишење."),mistake:commonMistake,exercises:pair("Front plank · Dead bug · Cable crunch","Преден планк · Dead bug · Кабелско свиткување")},
  {id:"quadriceps",view:"front",region:"legs",name:pair("Quadriceps","Квадрицепс"),scientific:"Quadriceps femoris",summary:pair("Four muscles across the front thigh that straighten the knee.","Четири мускули на предниот дел на бутот што го исправаат коленото."),function:pair("Extends the knee and controls stairs, landing, and rising.","Го исправа коленото и контролира скали, слетување и станување."),benefit:commonBenefit,training:pair("Use squats and split squats through a comfortable depth with stable feet.","Користи чучнувања и исчекори до удобна длабочина со стабилни стапала."),mistake:commonMistake,exercises:pair("Goblet squat · Split squat · Step-up","Гоблет чучнување · Исчекор · Качување")},
  {id:"tibialis",view:"front",region:"lower legs",name:pair("Tibialis anterior","Преден потколеничен мускул"),scientific:"Tibialis anterior",summary:pair("The muscle along the shin that lifts and controls the front of the foot.","Мускулот покрај потколеницата што го подигнува и контролира предниот дел на стапалото."),function:pair("Lifts the foot and controls how it meets the ground during walking.","Го подигнува стапалото и го контролира допирот со подлогата при одење."),benefit:commonBenefit,training:pair("Use controlled tibialis raises and heel walks without rushing repetitions.","Користи контролирани подигнувања на стапалото и одење на пети."),mistake:commonMistake,exercises:pair("Tibialis raise · Heel walk · Controlled step-down","Подигнување на стапалото · Одење на пети · Контролирано спуштање")},
  {id:"trapezius",view:"back",region:"upper back",name:pair("Trapezius","Трапез"),scientific:"Trapezius",summary:pair("A broad upper-back muscle that coordinates the shoulder blades.","Широк мускул на горниот грб што ги координира лопатките."),function:pair("Elevates, retracts, and upwardly rotates the shoulder blade.","Ја подигнува, повлекува и ротира лопатката нагоре."),benefit:commonBenefit,training:pair("Use rows, carries, and overhead work with a relaxed neck.","Користи веслања, носења и работа над глава со опуштен врат."),mistake:commonMistake,exercises:pair("Row · Farmer carry · Overhead press","Веслање · Фармерско носење · Потисок над глава")},
  {id:"latissimus",view:"back",region:"back",name:pair("Latissimus dorsi","Широк грбен мускул"),scientific:"Latissimus dorsi",summary:pair("The large side-back muscles that pull the upper arm down and back.","Големите странични грбни мускули што ја влечат раката надолу и назад."),function:pair("Extends and adducts the shoulder while contributing to trunk control.","Го исправа и приближува рамото и придонесува за контрола на трупот."),benefit:commonBenefit,training:pair("Use pulldowns and rows while allowing natural shoulder-blade movement.","Користи повлекувања и веслања со природно движење на лопатката."),mistake:commonMistake,exercises:pair("Lat pulldown · One-arm row · Assisted pull-up","Лат повлекување · Веслање со една рака · Потпомогнат згиб")},
  {id:"triceps",view:"back",region:"arms",name:pair("Triceps","Трицепс"),scientific:"Triceps brachii",summary:pair("The rear upper-arm muscle that straightens the elbow.","Задниот мускул на надлактицата што го исправа лактот."),function:pair("Extends the elbow and supports pressing and overhead arm control.","Го исправа лактот и помага при потисок и контрола над глава."),benefit:commonBenefit,training:pair("Use presses and extensions through a pain-free range.","Користи потисоци и екстензии во безболен опсег."),mistake:commonMistake,exercises:pair("Close-grip push-up · Cable extension · Overhead extension","Тесен склек · Кабелска екстензија · Екстензија над глава")},
  {id:"glutes",view:"back",region:"hips",name:pair("Gluteals","Глутеални мускули"),scientific:"Gluteus maximus and medius",summary:pair("The hip muscles that create extension and support pelvis control.","Мускулите на колкот што создаваат исправање и ја контролираат карлицата."),function:pair("Extends and stabilizes the hip during standing, walking, and lifting.","Го исправа и стабилизира колкот при стоење, одење и кревање."),benefit:commonBenefit,training:pair("Combine hip thrusts, squats, and split squats with full-foot pressure.","Комбинирај подигнување колкови, чучнувања и исчекори со стабилно стапало."),mistake:commonMistake,exercises:pair("Hip thrust · Squat · Split squat","Подигнување колкови · Чучнување · Исчекор")},
  {id:"hamstrings",view:"back",region:"legs",name:pair("Hamstrings","Задна ложа"),scientific:"Biceps femoris, semitendinosus, semimembranosus",summary:pair("The rear thigh muscles that bend the knee and extend the hip.","Задните бутни мускули што го свиткуваат коленото и го исправаат колкот."),function:pair("Flexes the knee, extends the hip, and helps decelerate the leg.","Го свиткува коленото, го исправа колкот и го забавува движењето на ногата."),benefit:commonBenefit,training:pair("Use Romanian deadlifts and leg curls with a controlled stretch.","Користи романско мртво кревање и прегиби со контролирано истегнување."),mistake:commonMistake,exercises:pair("Romanian deadlift · Leg curl · Hip hinge","Романско мртво кревање · Прегиб · Движење од колк")},
  {id:"calves",view:"back",region:"lower legs",name:pair("Calves","Листови"),scientific:"Gastrocnemius and soleus",summary:pair("The lower-leg muscles that propel and steady the body.","Мускулите на потколеницата што го придвижуваат и стабилизираат телото."),function:pair("Points the foot and controls the ankle during walking and running.","Го насочува стапалото и го контролира глуждот при одење и трчање."),benefit:commonBenefit,training:pair("Use straight- and bent-knee calf raises with controlled lowering.","Користи подигнувања со исправено и свиткано колено и контролирано спуштање."),mistake:commonMistake,exercises:pair("Standing calf raise · Seated calf raise · Loaded carry","Стоечко подигнување · Седечко подигнување · Носење товар")}
];

export function getMuscle(id: string) { return muscles.find((muscle) => muscle.id === id); }
export function getMusclesForView(view: MuscleView) { return muscles.filter((muscle) => muscle.view === view); }
