import type { Locale } from "@/lib/i18n/config";

type Pair = Record<Locale, string>;
export type MuscleView = "front" | "back";
type BaseMuscleSummary = {
  id: string; view: MuscleView; region: string; name: Pair; scientific: string; summary: Pair;
  function: Pair; benefit: Pair; training: Pair; mistake: Pair; exercises: Pair;
};
export type MuscleSummary = BaseMuscleSummary & {
  regionKey: string; location: Pair; origin: Pair; insertion: Pair;
  primaryMovements: Pair; secondaryMovements: Pair; activation: Pair;
  beginnerExercises: string[]; advancedExercises: string[];
  mobility: Pair; stretching: Pair; recovery: Pair; prevention: Pair;
  relatedMuscles: string[]; relatedArticles: string[];
};

const pair = (en: string, mk: string): Pair => ({ en, mk });
const commonBenefit = pair("Balanced training can improve joint control, everyday strength, and confidence in related movement patterns.", "Урамнотежениот тренинг може да ја подобри контролата на зглобовите, секојдневната сила и сигурноста во сродните движења.");
const commonMistake = pair("Adding load before the movement is controlled through a comfortable range.", "Додавање тежина пред движењето да биде контролирано во удобен опсег.");

const baseMuscles: BaseMuscleSummary[] = [
  {id:"pectorals",view:"front",region:"chest",name:pair("Pectorals","Градни мускули"),scientific:"Pectoralis major",summary:pair("The broad chest muscles used in pressing and bringing the arm across the body.","Широките градни мускули што учествуваат во потиснување и носење на раката кон телото."),function:pair("Moves the upper arm across the body and assists shoulder flexion and rotation.","Ја носи надлактицата кон телото и помага во свиткување и ротација на рамото."),benefit:commonBenefit,training:pair("Use push-ups and presses with a controlled lowering phase and comfortable shoulder position.","Користи склекови и потисоци со контролирано спуштање и удобна положба на рамото."),mistake:commonMistake,exercises:pair("Push-up · Dumbbell press · Cable press","Склек · Потисок со тегови · Кабелски потисок")},
  {id:"deltoids",view:"front",region:"shoulders",name:pair("Deltoids","Делтоидни мускули"),scientific:"Deltoideus",summary:pair("The rounded shoulder muscles that raise and rotate the arm.","Заоблените мускули на рамото што ја подигнуваат и ротираат раката."),function:pair("Raises the arm in several directions and helps center the shoulder joint.","Ја подигнува раката во повеќе насоки и помага во центрирање на рамениот зглоб."),benefit:commonBenefit,training:pair("Combine overhead presses with controlled lateral and rear-delt raises.","Комбинирај потисок над глава со контролирани странични и задни подигнувања."),mistake:commonMistake,exercises:pair("Overhead press · Lateral raise · Rear-delt raise","Потисок над глава · Странично подигнување · Задно подигнување")},
  {id:"biceps",view:"front",region:"arms",name:pair("Biceps","Бицепс"),scientific:"Biceps brachii",summary:pair("The front upper-arm muscles involved in bending the elbow and turning the palm.","Предните мускули на надлактицата што го свиткуваат лактот и ја вртат дланката."),function:pair("Flexes the elbow and turns the palm upward during pulling and carrying.","Го свиткува лактот и ја врти дланката нагоре при влечење и носење."),benefit:commonBenefit,training:pair("Use rows and curls while keeping the upper arm stable and wrist neutral.","Користи веслања и прегиби со стабилна надлактица и неутрален зглоб."),mistake:commonMistake,exercises:pair("Row · Curl · Chin-up","Веслање · Прегиб · Згиб")},
  {id:"abdominals",view:"front",region:"core",name:pair("Abdominals","Стомачни мускули"),scientific:"Rectus abdominis",summary:pair("The front trunk muscles that help control the relationship between ribs and pelvis.","Предните мускули на трупот што ја контролираат положбата на ребрата и карлицата."),function:pair("Flexes the trunk and resists excessive spinal extension.","Го свиткува трупот и се спротивставува на прекумерно истегнување на ’рбетот."),benefit:commonBenefit,training:pair("Use planks and controlled curl patterns while continuing to breathe.","Користи планк и контролирани свиткувања со непрекинато дишење."),mistake:commonMistake,exercises:pair("Front plank · Dead bug · Cable crunch","Преден планк · Dead bug · Кабелско свиткување")},
  {id:"quadriceps",view:"front",region:"legs",name:pair("Quadriceps","Квадрицепс"),scientific:"Quadriceps femoris",summary:pair("Four muscles across the front thigh that straighten the knee.","Четири мускули на предниот дел на бутот што го исправаат коленото."),function:pair("Extends the knee and controls stairs, landing, and rising.","Го исправа коленото и контролира скали, слетување и станување."),benefit:commonBenefit,training:pair("Use squats and split squats through a comfortable depth with stable feet.","Користи чучнувања и исчекори до удобна длабочина со стабилни стапала."),mistake:commonMistake,exercises:pair("Goblet squat · Split squat · Step-up","Гоблет чучнување · Исчекор · Качување")},
  {id:"tibialis",view:"front",region:"lower legs",name:pair("Tibialis anterior","Преден потколеничен мускул"),scientific:"Tibialis anterior",summary:pair("The muscle along the shin that lifts and controls the front of the foot.","Мускулот покрај потколеницата што го подигнува и контролира предниот дел на стапалото."),function:pair("Lifts the foot and controls how it meets the ground during walking.","Го подигнува стапалото и го контролира допирот со подлогата при одење."),benefit:commonBenefit,training:pair("Use controlled tibialis raises and heel walks without rushing repetitions.","Користи контролирани подигнувања на стапалото и одење на пети."),mistake:commonMistake,exercises:pair("Tibialis raise · Heel walk · Controlled step-down","Подигнување на стапалото · Одење на пети · Контролирано спуштање")},
  {id:"trapezius",view:"back",region:"upper back",name:pair("Trapezius","Трапез"),scientific:"Trapezius",summary:pair("A broad upper-back muscle that coordinates the shoulder blades.","Широк мускул на горниот грб што ги координира лопатките."),function:pair("Elevates, retracts, and upwardly rotates the shoulder blade.","Ја подигнува, повлекува и ротира лопатката нагоре."),benefit:commonBenefit,training:pair("Use rows, carries, and overhead work with a relaxed neck.","Користи веслања, носења и работа над глава со опуштен врат."),mistake:commonMistake,exercises:pair("Row · Farmer carry · Overhead press","Веслање · Фармерско носење · Потисок над глава")},
  {id:"latissimus",view:"back",region:"back",name:pair("Latissimus dorsi","Широк грбен мускул"),scientific:"Latissimus dorsi",summary:pair("The large side-back muscles that pull the upper arm down and back.","Големите странични грбни мускули што ја влечат раката надолу и назад."),function:pair("Extends and adducts the shoulder while contributing to trunk control.","Го исправа и приближува рамото и придонесува за контрола на трупот."),benefit:commonBenefit,training:pair("Use pulldowns and rows while allowing natural shoulder-blade movement.","Користи повлекувања и веслања со природно движење на лопатката."),mistake:commonMistake,exercises:pair("Lat pulldown · One-arm row · Assisted pull-up","Лат повлекување · Веслање со една рака · Потпомогнат згиб")},
  {id:"triceps",view:"back",region:"arms",name:pair("Triceps","Трицепс"),scientific:"Triceps brachii",summary:pair("The rear upper-arm muscle that straightens the elbow.","Задниот мускул на надлактицата што го исправа лактот."),function:pair("Extends the elbow and supports pressing and overhead arm control.","Го исправа лактот и помага при потисок и контрола над глава."),benefit:commonBenefit,training:pair("Use presses and extensions through a pain-free range.","Користи потисоци и екстензии во безболен опсег."),mistake:commonMistake,exercises:pair("Close-grip push-up · Cable extension · Overhead extension","Тесен склек · Кабелска екстензија · Екстензија над глава")},
  {id:"glutes",view:"back",region:"hips",name:pair("Gluteals","Глутеални мускули"),scientific:"Gluteus maximus and medius",summary:pair("The hip muscles that create extension and support pelvis control.","Мускулите на колкот што создаваат исправање и ја контролираат карлицата."),function:pair("Extends and stabilizes the hip during standing, walking, and lifting.","Го исправа и стабилизира колкот при стоење, одење и кревање."),benefit:commonBenefit,training:pair("Combine hip thrusts, squats, and split squats with full-foot pressure.","Комбинирај подигнување колкови, чучнувања и исчекори со стабилно стапало."),mistake:commonMistake,exercises:pair("Hip thrust · Squat · Split squat","Подигнување колкови · Чучнување · Исчекор")},
  {id:"hamstrings",view:"back",region:"legs",name:pair("Hamstrings","Задна ложа"),scientific:"Biceps femoris, semitendinosus, semimembranosus",summary:pair("The rear thigh muscles that bend the knee and extend the hip.","Задните бутни мускули што го свиткуваат коленото и го исправаат колкот."),function:pair("Flexes the knee, extends the hip, and helps decelerate the leg.","Го свиткува коленото, го исправа колкот и го забавува движењето на ногата."),benefit:commonBenefit,training:pair("Use Romanian deadlifts and leg curls with a controlled stretch.","Користи романско мртво кревање и прегиби со контролирано истегнување."),mistake:commonMistake,exercises:pair("Romanian deadlift · Leg curl · Hip hinge","Романско мртво кревање · Прегиб · Движење од колк")},
  {id:"calves",view:"back",region:"lower legs",name:pair("Calves","Листови"),scientific:"Gastrocnemius and soleus",summary:pair("The lower-leg muscles that propel and steady the body.","Мускулите на потколеницата што го придвижуваат и стабилизираат телото."),function:pair("Points the foot and controls the ankle during walking and running.","Го насочува стапалото и го контролира глуждот при одење и трчање."),benefit:commonBenefit,training:pair("Use straight- and bent-knee calf raises with controlled lowering.","Користи подигнувања со исправено и свиткано колено и контролирано спуштање."),mistake:commonMistake,exercises:pair("Standing calf raise · Seated calf raise · Loaded carry","Стоечко подигнување · Седечко подигнување · Носење товар")}
];

type Detail = {
  location: Pair; origin: Pair; insertion: Pair; primaryMovements: Pair;
  relatedMuscles: string[]; beginnerExercises: string[]; advancedExercises: string[];
  relatedArticles: string[];
};
const details: Record<string, Detail> = {
  pectorals: { location: pair("Across the front of the upper chest.","На предната страна на горниот дел од градниот кош."), origin: pair("Clavicle, sternum, and upper costal cartilage.","Клучна коска, градна коска и горните ребрени ’рскавици."), insertion: pair("Upper humerus at the lateral lip of the intertubercular groove.","Горниот дел на надлактичната коска."), primaryMovements: pair("Horizontal adduction and internal rotation of the shoulder.","Хоризонтално приближување и внатрешна ротација на рамото."), relatedMuscles:["deltoids","triceps"], beginnerExercises:["push-up"], advancedExercises:["dumbbell-bench-press"], relatedArticles:["progressive-overload-for-beginners"] },
  deltoids: { location: pair("Capping the front, side, and rear of the shoulder.","На предната, страничната и задната страна на рамото."), origin: pair("Clavicle, acromion, and spine of the scapula.","Клучна коска, акромион и гребен на лопатката."), insertion: pair("Deltoid tuberosity of the humerus.","Делтоидната грубост на надлактичната коска."), primaryMovements: pair("Shoulder flexion, abduction, and extension by region.","Свиткување, оддалечување и исправање на рамото според делот."), relatedMuscles:["pectorals","trapezius","triceps"], beginnerExercises:["overhead-press"], advancedExercises:["farmer-carry"], relatedArticles:["muscles-of-the-back-made-simple"] },
  biceps: { location: pair("Front of the upper arm between shoulder and elbow.","На предната страна на надлактицата."), origin: pair("Two heads from the scapula.","Две глави што започнуваат од лопатката."), insertion: pair("Radius and forearm fascia.","Палечната коска и фасцијата на подлактицата."), primaryMovements: pair("Elbow flexion and forearm supination.","Свиткување на лактот и вртење на дланката нагоре."), relatedMuscles:["triceps","latissimus"], beginnerExercises:["one-arm-row"], advancedExercises:["lat-pulldown"], relatedArticles:["progressive-overload-for-beginners"] },
  abdominals: { location: pair("Front wall of the trunk between ribs and pelvis.","Предниот ѕид на трупот меѓу ребрата и карлицата."), origin: pair("Pubic crest and pubic symphysis.","Срамната коска и срамната симфиза."), insertion: pair("Lower sternum and costal cartilages five to seven.","Долниот дел на градната коска и ребрените ’рскавици."), primaryMovements: pair("Trunk flexion and control of spinal extension.","Свиткување на трупот и контрола на ’рбетната екстензија."), relatedMuscles:["glutes"], beginnerExercises:["dead-bug"], advancedExercises:["side-plank"], relatedArticles:["progressive-overload-for-beginners"] },
  quadriceps: { location: pair("Front and sides of the thigh.","На предната и страничната страна на бутот."), origin: pair("Pelvis and upper femur, depending on the head.","Карлицата и горниот дел на бутната коска, зависно од главата."), insertion: pair("Tibial tuberosity through the patella and patellar tendon.","Потколеницата преку чашката и пателарната тетива."), primaryMovements: pair("Knee extension; rectus femoris also assists hip flexion.","Исправање на коленото; правиот бутен мускул помага и во свиткување на колкот."), relatedMuscles:["hamstrings","glutes","calves"], beginnerExercises:["bodyweight-squat"], advancedExercises:["goblet-squat"], relatedArticles:["progressive-overload-for-beginners"] },
  tibialis: { location: pair("Along the outer front edge of the shin.","По предниот надворешен раб на потколеницата."), origin: pair("Upper lateral tibia and nearby membrane.","Горниот надворешен дел на потколеницата и соседната мембрана."), insertion: pair("Medial foot at the first metatarsal and cuneiform.","Внатрешниот дел на стапалото."), primaryMovements: pair("Ankle dorsiflexion and inversion.","Подигнување и навнатрешно насочување на стапалото."), relatedMuscles:["calves","quadriceps"], beginnerExercises:["bodyweight-squat"], advancedExercises:["farmer-carry"], relatedArticles:["muscle-soreness-normal-or-warning"] },
  trapezius: { location: pair("From the neck across the shoulders to the middle back.","Од вратот преку рамената до средниот грб."), origin: pair("Skull base, neck ligament, and upper thoracic spine.","Основата на черепот, вратниот лигамент и горниот граден ’рбет."), insertion: pair("Clavicle and spine of the scapula.","Клучната коска и гребенот на лопатката."), primaryMovements: pair("Scapular elevation, retraction, depression, and upward rotation.","Подигнување, повлекување, спуштање и нагорна ротација на лопатката."), relatedMuscles:["deltoids","latissimus"], beginnerExercises:["one-arm-row"], advancedExercises:["farmer-carry"], relatedArticles:["muscles-of-the-back-made-simple"] },
  latissimus: { location: pair("Broadly across the lower and side back into the upper arm.","Широко по долниот и страничниот грб до надлактицата."), origin: pair("Lower thoracic spine, thoracolumbar fascia, pelvis, and lower ribs.","Долниот граден ’рбет, фасцијата, карлицата и долните ребра."), insertion: pair("Front of the upper humerus.","Предниот горен дел на надлактичната коска."), primaryMovements: pair("Shoulder extension, adduction, and internal rotation.","Исправање, приближување и внатрешна ротација на рамото."), relatedMuscles:["trapezius","biceps"], beginnerExercises:["one-arm-row"], advancedExercises:["lat-pulldown"], relatedArticles:["muscles-of-the-back-made-simple"] },
  triceps: { location: pair("Rear of the upper arm.","На задната страна на надлактицата."), origin: pair("Scapula and rear humerus across three heads.","Лопатката и задната страна на надлактичната коска преку три глави."), insertion: pair("Olecranon of the ulna.","Лакотниот израсток на лакотната коска."), primaryMovements: pair("Elbow extension; the long head also assists shoulder extension.","Исправање на лактот; долгата глава помага и во исправање на рамото."), relatedMuscles:["biceps","pectorals","deltoids"], beginnerExercises:["push-up"], advancedExercises:["overhead-press"], relatedArticles:["progressive-overload-for-beginners"] },
  glutes: { location: pair("Back and outer surface of the pelvis and hip.","На задната и надворешната страна на карлицата и колкот."), origin: pair("Back of the pelvis, sacrum, and surrounding fascia.","Задниот дел на карлицата, крсната коска и соседната фасција."), insertion: pair("Upper femur and iliotibial tract.","Горниот дел на бутната коска и илиотибијалниот тракт."), primaryMovements: pair("Hip extension, abduction, rotation, and pelvic control.","Исправање, оддалечување, ротација на колкот и контрола на карлицата."), relatedMuscles:["hamstrings","quadriceps","abdominals"], beginnerExercises:["hip-bridge"], advancedExercises:["romanian-deadlift"], relatedArticles:["progressive-overload-for-beginners"] },
  hamstrings: { location: pair("Back of the thigh from pelvis to below the knee.","На задната страна на бутот од карлицата до под коленото."), origin: pair("Mostly the sitting bone of the pelvis.","Главно седалната коска на карлицата."), insertion: pair("Upper tibia and fibula.","Горниот дел на потколеничните коски."), primaryMovements: pair("Knee flexion and hip extension.","Свиткување на коленото и исправање на колкот."), relatedMuscles:["glutes","quadriceps","calves"], beginnerExercises:["hip-bridge"], advancedExercises:["romanian-deadlift"], relatedArticles:["muscle-soreness-normal-or-warning"] },
  calves: { location: pair("Back of the lower leg below the knee.","На задната страна на потколеницата."), origin: pair("Lower femur and rear tibia/fibula.","Долниот дел на бутната коска и задната потколеница."), insertion: pair("Heel bone through the Achilles tendon.","Петната коска преку Ахиловата тетива."), primaryMovements: pair("Ankle plantar flexion; gastrocnemius also assists knee flexion.","Насочување на стапалото надолу; гастрокнемиусот помага и во свиткување на коленото."), relatedMuscles:["tibialis","hamstrings","quadriceps"], beginnerExercises:["bodyweight-squat"], advancedExercises:["farmer-carry"], relatedArticles:["muscle-soreness-normal-or-warning"] }
};

const commonSecondary = pair("Works with nearby muscles to steady the joint and control the return phase.", "Работи со соседните мускули за стабилизација на зглобот и контрола на враќањето.");
const commonActivation = pair("Use a light first set, a controlled range, and the cue that best keeps the intended joint moving smoothly.", "Користи лесна прва серија, контролиран опсег и насока што го одржува зглобот во мирно движење.");
const commonMobility = pair("Explore the related joint through a comfortable active range before adding load.", "Истражи го поврзаниот зглоб низ удобен активен опсег пред додавање товар.");
const commonStretching = pair("Use a mild, steady position without bouncing or forcing numbness, tingling, or pain.", "Користи блага и мирна положба без нишање или предизвикување трнење и болка.");
const commonRecovery = pair("Allow symptoms from normal effort to settle, keep general movement comfortable, and adjust the next dose when needed.", "Остави ги вообичаените знаци на напор да се смират, движи се удобно и прилагоди ја следната доза.");
const commonPrevention = pair("Progress volume and load gradually, keep technique repeatable, and seek qualified assessment for new or persistent pain.", "Зголемувај ги обемот и товарот постепено, одржувај повторлива техника и побарај стручна проценка за нова или постојана болка.");

export const muscles: MuscleSummary[] = baseMuscles.map((muscle) => {
  const detail = details[muscle.id];
  return { ...muscle, regionKey: ["quadriceps","hamstrings","calves","tibialis"].includes(muscle.id) ? "legs" : muscle.region.replace(/\s+/g,"-"),
    location: detail.location, origin: detail.origin, insertion: detail.insertion,
    primaryMovements: detail.primaryMovements, secondaryMovements: commonSecondary, activation: commonActivation,
    beginnerExercises: detail.beginnerExercises, advancedExercises: detail.advancedExercises,
    mobility: commonMobility, stretching: commonStretching, recovery: commonRecovery, prevention: commonPrevention,
    relatedMuscles: detail.relatedMuscles, relatedArticles: detail.relatedArticles };
});

export function getMuscle(id: string) { return muscles.find((muscle) => muscle.id === id); }
export function getMusclesForView(view: MuscleView) { return muscles.filter((muscle) => muscle.view === view); }
const regionLabels: Record<string, { en: string; mk: string }> = {
  arms: { en: "Arms", mk: "Раце" },
  back: { en: "Back", mk: "Грб" },
  chest: { en: "Chest", mk: "Гради" },
  core: { en: "Core", mk: "Труп" },
  hips: { en: "Hips", mk: "Колкови" },
  legs: { en: "Legs", mk: "Нозе" },
  "lower legs": { en: "Lower legs", mk: "Потколеници" },
  "lower-legs": { en: "Lower legs", mk: "Потколеници" },
  shoulders: { en: "Shoulders", mk: "Рамена" },
  "upper back": { en: "Upper back", mk: "Горен грб" },
  "upper-back": { en: "Upper back", mk: "Горен грб" },
};
export function regionLabel(region: string, locale: "en" | "mk") {
  return regionLabels[region]?.[locale] ?? region.replaceAll("-", " ");
}
export function getAnatomyRegions() { return [...new Set(muscles.map((muscle) => muscle.regionKey))].sort(); }
export function searchMuscles(query: string, region = "all") {
  const needle = query.trim().toLocaleLowerCase();
  const aliases: Record<string, string> = { pectorals: "chest гради", deltoids: "shoulder рамо", abdominals: "stomach core стомак труп", quadriceps: "thigh бут", latissimus: "back грб", glutes: "hips колкови", calves: "lower leg потколеница" };
  return muscles.filter((muscle) => (region === "all" || muscle.regionKey === region) &&
    (!needle || [muscle.id,muscle.name.en,muscle.name.mk,muscle.scientific,muscle.region,muscle.regionKey,muscle.summary.en,muscle.summary.mk,muscle.location.en,muscle.location.mk,aliases[muscle.id] ?? ""].join(" ").toLocaleLowerCase().includes(needle)));
}
export function resolveRelatedMuscles(muscle: MuscleSummary) {
  return muscle.relatedMuscles.map(getMuscle).filter((item): item is MuscleSummary => item !== undefined && item.id !== muscle.id);
}
