import type { Locale } from "@/lib/i18n/config";

const trackingContent = {
  en: {
    nav: { today: "Today", progress: "Progress", habits: "Habits", goals: "Goals", notifications: "Notifications", anatomy: "Anatomy", knowledge: "Knowledge" },
    today: { greeting: "Good to see you", subtitle: "A calm view of what matters today.", next: "Next useful action", balance: "Daily balance", rhythm: "Your rhythm", guidance: "A useful nudge", water: "Water", habits: "Habits", goals: "Active goals", weight: "Latest weight", noTarget: "Set a water target to see progress", allDone: "Your tracked actions are complete for today.", logged: "Logged", remaining: "Remaining", noActivity: "No tracked activity yet today." },
    forms: { addWater: "Add water", amount: "Amount", saveWeight: "Save weight", weight: "Weight", date: "Date", note: "Note (optional)", addHabit: "Add habit", habitName: "Habit name", addGoal: "Add goal", goalName: "Goal name", target: "Target (optional)", unit: "Unit (optional)", endDate: "End date (optional)", saving: "Saving…", delete: "Delete", archive: "Archive", complete: "Complete", skip: "Skip", clear: "Clear", pause: "Pause", resume: "Resume", markRead: "Mark as read", markAllRead: "Mark all as read" },
    empty: { habits: "No daily habits yet. Add one small action you can repeat.", goals: "No goals yet. Create one that is specific and useful to you.", weight: "Add your first measurement to establish a private baseline.", notifications: "You're all caught up. New product notifications will appear here.", water: "No water logged today." },
    pages: { habits: "Daily habits", habitsIntro: "Keep the list short enough to act on.", goals: "Goals", goalsIntro: "Set direction without turning wellbeing into a scoreboard.", progress: "Progress", progressIntro: "Review real changes and consistency over time.", notifications: "Notifications", notificationsIntro: "Important account and product updates, without noise.", consistency: "Seven-day consistency", history: "Weight history" },
    status: { active: "Active", paused: "Paused", complete: "Complete", skipped: "Skipped", unread: "Unread", read: "Read" },
    guidance: { water: "A small water entry is the clearest next step.", habit: "Complete one pending habit before adding more.", goal: "Review an active goal and decide the next concrete action.", weight: "Add a baseline measurement only if tracking weight is useful to you.", complete: "Your tracked items are complete. Consistency includes stopping for the day." },
  },
  mk: {
    nav: { today: "Денес", progress: "Напредок", habits: "Навики", goals: "Цели", notifications: "Известувања", anatomy: "Анатомија", knowledge: "Знаење" },
    today: { greeting: "Добро е што сте тука", subtitle: "Смирен преглед на она што е важно денес.", next: "Следна корисна активност", balance: "Дневна рамнотежа", rhythm: "Вашиот ритам", guidance: "Корисен поттик", water: "Вода", habits: "Навики", goals: "Активни цели", weight: "Последна тежина", noTarget: "Поставете цел за вода за да го видите напредокот", allDone: "Вашите следени активности се завршени за денес.", logged: "Евидентирано", remaining: "Преостанува", noActivity: "Сè уште нема следена активност денес." },
    forms: { addWater: "Додај вода", amount: "Количина", saveWeight: "Зачувај тежина", weight: "Тежина", date: "Датум", note: "Белешка (незадолжително)", addHabit: "Додај навика", habitName: "Име на навика", addGoal: "Додај цел", goalName: "Име на цел", target: "Целна вредност (незадолжително)", unit: "Единица (незадолжително)", endDate: "Краен датум (незадолжително)", saving: "Се зачувува…", delete: "Избриши", archive: "Архивирај", complete: "Заврши", skip: "Прескокни", clear: "Исчисти", pause: "Паузирај", resume: "Продолжи", markRead: "Означи како прочитано", markAllRead: "Означи ги сите како прочитани" },
    empty: { habits: "Сè уште нема дневни навики. Додајте една мала активност што можете да ја повторувате.", goals: "Сè уште нема цели. Создајте цел што е конкретна и корисна за вас.", weight: "Додајте го првото мерење за да поставите приватна основа.", notifications: "Сè е прегледано. Новите известувања ќе се појават тука.", water: "Денес нема евидентирана вода." },
    pages: { habits: "Дневни навики", habitsIntro: "Нека списокот биде доволно краток за да дејствувате.", goals: "Цели", goalsIntro: "Поставете насока без здравјето да стане табела со резултати.", progress: "Напредок", progressIntro: "Прегледајте ги вистинските промени и доследноста со текот на времето.", notifications: "Известувања", notificationsIntro: "Важни новости за сметката и производот, без бучава.", consistency: "Доследност во седум дена", history: "Историја на тежината" },
    status: { active: "Активна", paused: "Паузирана", complete: "Завршена", skipped: "Прескокната", unread: "Непрочитано", read: "Прочитано" },
    guidance: { water: "Мал внес на вода е најјасниот следен чекор.", habit: "Завршете една навика пред да додадете повеќе.", goal: "Прегледајте активна цел и одберете конкретен следен чекор.", weight: "Додајте основно мерење само ако следењето тежина ви е корисно.", complete: "Следените активности се завршени. Доследноста вклучува и запирање за денес." },
  },
} as const;

export function getTrackingContent(locale: Locale) { return trackingContent[locale]; }
