export const publicHumanRoutes = [
  "/",
  "/features",
  "/features/nutrition",
  "/features/training",
  "/anatomy",
  "/anatomy/pectorals",
  "/blog",
  "/about",
  "/contact",
  "/privacy",
  "/terms",
  "/sign-in",
  "/sign-up",
  "/magic-link",
  "/forgot-password",
  "/reset-password",
  "/~offline",
] as const;

export const machineRoutes = [
  "/manifest.webmanifest",
  "/robots.txt",
  "/sitemap.xml",
  "/feed.xml",
  "/sw.js",
] as const;

export const protectedRoutes = [
  "/today",
  "/nutrition",
  "/meal-planner",
  "/recipes",
  "/recipes/oat-banana-breakfast",
  "/grocery-list",
  "/training",
  "/training/planner",
  "/workouts",
  "/workouts/new",
  "/workouts/00000000-0000-4000-8000-000000000000",
  "/workouts/00000000-0000-4000-8000-000000000000/edit",
  "/exercises",
  "/exercises/bodyweight-squat",
  "/workout-history",
  "/workout-history/00000000-0000-4000-8000-000000000000",
  "/personal-records",
  "/session/00000000-0000-4000-8000-000000000000",
  "/progress",
  "/goals",
  "/habits",
  "/notifications",
  "/assistant",
  "/onboarding",
] as const;

export const responsiveRoutes = [
  "/",
  "/features",
  "/features/nutrition",
  "/features/training",
  "/anatomy",
  "/anatomy/pectorals",
  "/blog",
  "/blog/progressive-overload-for-beginners",
  "/about",
  "/contact",
  "/privacy",
  "/terms",
  "/sign-in",
  "/sign-up",
  "/magic-link",
  "/forgot-password",
  "/reset-password",
  "/~offline",
] as const;

export const authenticatedResponsiveRoutes = [
  "/today",
  "/nutrition",
  "/meal-planner",
  "/recipes",
  "/grocery-list",
  "/training",
  "/training/planner",
  "/workouts",
  "/exercises",
  "/workout-history",
  "/personal-records",
  "/progress",
  "/goals",
  "/habits",
  "/notifications",
  "/assistant",
] as const;
