import Link from "next/link";
import { ArrowRight, CheckCircle2, Droplets, Flag, Repeat2, Scale, Soup } from "lucide-react";
import { Button } from "@/components/ui/button";
import { DailyBalance } from "@/features/dashboard/daily-balance";
import { GuidancePanel } from "@/features/dashboard/guidance-panel";
import { RhythmRail } from "@/features/dashboard/rhythm-rail";
import { WaterForm } from "@/features/tracking/tracking-form";
import { kgToLb, mlToFluidOunces } from "@/features/tracking/domain";
import { getTrackingContent } from "@/features/tracking/content";
import type { Locale } from "@/lib/i18n/config";
import type { NextAction } from "@/features/tracking/types";

type Props = { locale: Locale; name: string; date: string; units: "metric" | "imperial"; summary: { waterMl: number; waterTargetMl: number | null; energyKcal: number; energyTargetKcal: number | null; completedHabits: number; totalHabits: number; activeGoals: number; latestWeightKg: number | null; waterRatio: number | null; habitRatio: number | null; nextAction: NextAction }; waterEntries: Array<{ id: string; amountMl: number; loggedAt: string }>; habits: Array<{ id: string; title: string; status: "complete" | "skipped" | null }> };

export function TodayCanvas({ locale, name, date, units, summary, waterEntries, habits }: Props) {
  const c = getTrackingContent(locale); const language = locale === "mk" ? "mk-MK" : "en-GB";
  const water = (ml: number) => units === "metric" ? `${new Intl.NumberFormat(language).format(ml)} ml` : `${new Intl.NumberFormat(language, { maximumFractionDigits: 1 }).format(mlToFluidOunces(ml))} fl oz`;
  const actionCopy = summary.nextAction.kind === "water" ? c.forms.addWater : summary.nextAction.kind === "habit" ? summary.nextAction.label : summary.nextAction.kind === "goal" ? c.nav.goals : summary.nextAction.kind === "weight" ? c.forms.saveWeight : c.today.allDone;
  const guidance = c.guidance[summary.nextAction.kind];
  const energyRatio = summary.energyTargetKcal ? Math.min(1, summary.energyKcal / summary.energyTargetKcal) : null;
  return <main id="main-content" className="shell today-canvas"><header className="tracking-page-header"><div><p className="eyebrow">{new Intl.DateTimeFormat(language, { weekday: "long", day: "numeric", month: "long" }).format(new Date(`${date}T12:00:00`))}</p><h1>{c.today.greeting}, {name}</h1><p>{c.today.subtitle}</p></div></header><div className="today-layout"><div className="today-primary"><section className="next-action-panel"><div><p className="eyebrow">{c.today.next}</p><h2>{actionCopy}</h2><p>{guidance}</p></div>{summary.nextAction.kind === "water" ? <WaterForm labels={c.forms} units={units} /> : <Button asChild><Link href={summary.nextAction.href}>{actionCopy}<ArrowRight /></Link></Button>}</section><DailyBalance title={c.today.balance} rows={[{ label: locale === "mk" ? "Енергија" : "Energy", value: summary.energyTargetKcal ? `${Math.round(summary.energyKcal)} / ${Math.round(summary.energyTargetKcal)} kcal` : `${Math.round(summary.energyKcal)} kcal`, ratio: energyRatio, note: energyRatio === null ? (locale === "mk" ? "Поставете цел за енергија во поставките." : "Set an energy target in settings.") : undefined }, { label: c.today.water, value: summary.waterTargetMl ? `${water(summary.waterMl)} / ${water(summary.waterTargetMl)}` : water(summary.waterMl), ratio: summary.waterRatio, note: c.today.noTarget }, { label: c.today.habits, value: `${summary.completedHabits} / ${summary.totalHabits}`, ratio: summary.habitRatio, note: summary.totalHabits ? undefined : c.empty.habits }, { label: c.today.goals, value: String(summary.activeGoals), ratio: null, note: summary.activeGoals ? c.status.active : c.empty.goals }, { label: c.today.weight, value: summary.latestWeightKg === null ? "—" : units === "metric" ? `${summary.latestWeightKg.toFixed(1)} kg` : `${kgToLb(summary.latestWeightKg).toFixed(1)} lb`, ratio: null, note: summary.latestWeightKg === null ? c.empty.weight : c.today.logged }]} /><RhythmRail title={c.today.rhythm} waterTitle={c.today.water} waterEntries={waterEntries.map((entry) => ({ id: entry.id, amount: water(entry.amountMl), time: new Intl.DateTimeFormat(language, { hour: "2-digit", minute: "2-digit" }).format(new Date(entry.loggedAt)) }))} habits={habits} statusLabels={{ complete: c.status.complete, skipped: c.status.skipped, remaining: c.today.remaining }} /></div><div className="today-secondary"><GuidancePanel eyebrow={c.today.guidance} title={actionCopy} body={guidance} href={summary.nextAction.href} action={actionCopy} /><section className="tracking-key"><h2>{locale === "mk" ? "Што е поврзано" : "What is connected"}</h2><ul><li><Soup /><Link href="/nutrition">{locale === "mk" ? "Исхрана" : "Nutrition"}</Link></li><li><Droplets />{c.today.water}</li><li><Repeat2 />{c.today.habits}</li><li><Flag />{c.today.goals}</li><li><Scale />{c.today.weight}</li></ul>{summary.nextAction.kind === "complete" && <p><CheckCircle2 />{c.today.allDone}</p>}</section></div></div></main>;
}
