import type { Locale } from "@/lib/i18n/config";

export const fitnessContent = {
  en: {
    training: "Training",
    trainingEyebrow: "Move with direction",
    trainingIntro: "Plan clearly, train with focus, and keep a record you can trust.",
    exercises: "Exercise library",
    workouts: "My workouts",
    planner: "Weekly planner",
    history: "Workout history",
    records: "Personal records",
    create: "Create workout",
    start: "Start workout",
    resume: "Resume session",
    unavailable: "Saved workouts are temporarily unavailable. Your library and ideas still work.",
    storageUnavailable: "Workout storage is temporarily unavailable. Please try again shortly.",
    toolPlanner: "See and shape the next seven days",
    toolWorkouts: "Build and reuse your routines",
    toolExercises: (count: number) => `Explore ${count} guided movements`,
    toolHistory: "Review completed work",
    toolRecords: "See genuine bests",
    toolsLabel: "Training tools",
    nextOn: (date: string) => `Next · ${date}`,
    readyWhenYouAre: "Ready when you are",
    chooseStart: "Choose a useful starting point",
    templateMeta: (minutes: number, goal: string) => `${minutes} minutes · ${goal}`,
    browseHint: "Browse a complete idea, adapt it, and save only what fits.",
    browseIdeas: "Browse ideas",
    // workouts list
    workoutsEyebrow: "Reusable structure",
    workoutsIntro: "Build routines once, schedule them, and keep every completed session intact.",
    readyDescription: "Ready when you are.",
    min: "min",
    firstWorkoutTitle: "Build your first repeatable workout",
    firstWorkoutBody: "Start with a small routine you can complete confidently.",
    // workout detail
    templateEyebrow: "Workout template",
    templateFallback: "A focused sequence for your next session.",
    edit: "Edit",
    sessionPlan: "Session plan",
    exercise: "Exercise",
    sets: "sets",
    reps: "reps",
    rest: "rest",
    putOnWeek: "Put it on your week",
    date: "Date",
    schedule: "Schedule",
    deleteTemplate: "Delete template",
    // builder pages
    editorEyebrow: "Workout editor",
    editTitle: (name: string) => `Edit ${name}`,
    editIntro: "Completed sessions remain unchanged when you refine this template.",
    adaptIdea: "Adapt a starting idea",
    builderEyebrow: "Workout builder",
    createTitle: "Create a workout",
    createIntro: "Choose a clear sequence now so training feels simpler later.",
    // builder component
    workoutName: "Workout name",
    namePlaceholder: "e.g. Full body A",
    expectedDuration: "Expected duration (min)",
    description: "Description",
    descriptionPlaceholder: "What is this session for?",
    sec: "sec",
    addAtLeastOne: "Add at least one exercise to save this workout.",
    saveWorkout: "Save workout",
    saving: "Saving…",
    addMovement: "Add movement",
    searchMovements: "Filter movements",
    reorderOrRemove: (name: string) => `Reorder or remove ${name}`,
    moveUp: (name: string) => `Move ${name} up`,
    moveDown: (name: string) => `Move ${name} down`,
    remove: (name: string) => `Remove ${name}`,
    add: (name: string) => `Add ${name}`,
    // history
    historyEyebrow: "Completed work",
    historyIntro: "Your record stays faithful to what happened on the day.",
    noHistoryTitle: "No completed workouts yet",
    noHistoryBody: "Finish a logged session and it will appear here.",
    goToTraining: "Go to training",
    sessionRecord: (date: string) => `Session record · ${date}`,
    sessionSummary: (sets: number, reps: number, volume: number) => `${sets} completed sets · ${reps} reps · ${volume} kg volume`,
    set: "Set",
    bodyweight: "Bodyweight",
    // planner
    plannerEyebrow: "Seven-day rhythm",
    plannerTitle: "Training planner",
    plannerIntro: "Keep your week visible without turning it into a crowded calendar.",
    manageWorkouts: "Manage workouts",
    workout: "Workout",
    planned: "Planned",
    skipped: "Skipped",
    restore: "Restore",
    skip: "Skip",
    openDay: "Open day",
    scheduleWorkout: "Schedule a workout",
    addToWeek: "Add to week",
    createBeforeScheduling: "Create a workout before scheduling.",
    // session
    activeSession: "Active session",
    started: (time: string) => `Started ${time}`,
    discard: "Discard",
    discardConfirm: "Discard this session? Logged sets will not be saved.",
    needOneSet: "Complete at least one set before finishing.",
    kg: "kg",
    done: "Done",
    loadLabel: "Load in kilograms",
    repsLabel: "Repetitions",
    completeLabel: "Set complete",
    save: "Save",
    saveSet: (n: number) => `Save set ${n}`,
    removeSet: (n: number) => `Remove set ${n}`,
    addSet: "Add set",
    finishWorkout: "Finish workout",
    // records
    recordsEyebrow: "Evidence of progress",
    recordsIntro: "Only completed sets count. These are observed bests, not estimated one-rep maximums.",
    noRecordsTitle: "Your records begin with completed work",
    noRecordsBody: "Complete a workout and mark its sets done to build this view.",
    personalBests: "Personal bests",
    heaviestLoad: "Heaviest load",
    mostReps: "Most repetitions",
    bestSetVolume: "Best set volume",
    bestSessionVolume: "Best session volume",
    latestAchievement: (date: string) => `Latest achievement · ${date}`,
    // exercises
    catalogueEyebrow: "Movement catalogue",
    catalogueIntro: "Clear instructions, target muscles, and practical equipment guidance.",
  },
  mk: {
    training: "Тренинг",
    trainingEyebrow: "Движење со насока",
    trainingIntro: "Планирајте јасно, тренирајте фокусирано и чувајте сигурна евиденција.",
    exercises: "Библиотека на вежби",
    workouts: "Мои тренинзи",
    planner: "Неделен планер",
    history: "Историја на тренинзи",
    records: "Лични рекорди",
    create: "Создај тренинг",
    start: "Започни тренинг",
    resume: "Продолжи сесија",
    unavailable: "Зачуваните тренинзи се привремено недостапни. Библиотеката и идеите сè уште работат.",
    storageUnavailable: "Складиштето за тренинзи е привремено недостапно. Обидете се повторно наскоро.",
    toolPlanner: "Видете ги и обликувајте ги следните седум дена",
    toolWorkouts: "Креирајте и повторно користете рутини",
    toolExercises: (count: number) => `Истражете ${count} водени движења`,
    toolHistory: "Прегледајте завршени тренинзи",
    toolRecords: "Видете ги вистинските рекорди",
    toolsLabel: "Алатки за тренинг",
    nextOn: (date: string) => `Следно · ${date}`,
    readyWhenYouAre: "Спремно кога сте вие",
    chooseStart: "Изберете корисна почетна точка",
    templateMeta: (minutes: number, goal: string) => `${minutes} минути · ${goal}`,
    browseHint: "Прегледајте цела идеја, прилагодете ја и зачувајте само она што ви одговара.",
    browseIdeas: "Прегледај идеи",
    workoutsEyebrow: "Структура за повторување",
    workoutsIntro: "Креирајте рутини еднаш, закажете ги и чувајте ја секоја завршена сесија.",
    readyDescription: "Спремно кога сте вие.",
    min: "мин",
    firstWorkoutTitle: "Креирајте го првиот тренинг за повторување",
    firstWorkoutBody: "Започнете со мала рутина што можете сигурно да ја завршите.",
    templateEyebrow: "Шаблон за тренинг",
    templateFallback: "Фокусирана низа за вашата следна сесија.",
    edit: "Уреди",
    sessionPlan: "План на сесијата",
    exercise: "Вежба",
    sets: "серии",
    reps: "повт.",
    rest: "одмор",
    putOnWeek: "Ставете го во неделата",
    date: "Датум",
    schedule: "Закажи",
    deleteTemplate: "Избриши шаблон",
    editorEyebrow: "Уредувач на тренинг",
    editTitle: (name: string) => `Уреди: ${name}`,
    editIntro: "Завршените сесии остануваат непроменети кога го подобрувате шаблонот.",
    adaptIdea: "Прилагодете почетна идеја",
    builderEyebrow: "Креатор на тренинг",
    createTitle: "Создај тренинг",
    createIntro: "Изберете јасна низа сега за тренингот подоцна да биде поедноставен.",
    workoutName: "Име на тренингот",
    namePlaceholder: "пр. Цело тело А",
    expectedDuration: "Очекувано времетраење (мин)",
    description: "Опис",
    descriptionPlaceholder: "За што е оваа сесија?",
    sec: "сек",
    addAtLeastOne: "Додадете барем една вежба за да го зачувате тренингот.",
    saveWorkout: "Зачувај тренинг",
    saving: "Се зачувува…",
    addMovement: "Додај движење",
    searchMovements: "Филтрирај движења",
    reorderOrRemove: (name: string) => `Преуреди или отстрани ${name}`,
    moveUp: (name: string) => `Помести ${name} нагоре`,
    moveDown: (name: string) => `Помести ${name} надолу`,
    remove: (name: string) => `Отстрани ${name}`,
    add: (name: string) => `Додај ${name}`,
    historyEyebrow: "Завршена работа",
    historyIntro: "Вашата евиденција останува верна на она што се случило тој ден.",
    noHistoryTitle: "Сè уште нема завршени тренинзи",
    noHistoryBody: "Завршете евидентирана сесија и таа ќе се појави тука.",
    goToTraining: "Оди на тренинг",
    sessionRecord: (date: string) => `Запис од сесија · ${date}`,
    sessionSummary: (sets: number, reps: number, volume: number) => `${sets} завршени серии · ${reps} повторувања · ${volume} kg волумен`,
    set: "Серија",
    bodyweight: "Сопствена тежина",
    plannerEyebrow: "Седумдневен ритам",
    plannerTitle: "Планер за тренинг",
    plannerIntro: "Нека неделата биде прегледна без да стане преполн календар.",
    manageWorkouts: "Управувај со тренинзи",
    workout: "Тренинг",
    planned: "Планирано",
    skipped: "Прескокнато",
    restore: "Врати",
    skip: "Прескокни",
    openDay: "Слободен ден",
    scheduleWorkout: "Закажи тренинг",
    addToWeek: "Додај во неделата",
    createBeforeScheduling: "Создајте тренинг пред закажување.",
    activeSession: "Активна сесија",
    started: (time: string) => `Започната во ${time}`,
    discard: "Откажи сесија",
    discardConfirm: "Да се откаже сесијата? Евидентираните серии нема да се зачуваат.",
    needOneSet: "Завршете барем една серија пред да завршите.",
    kg: "kg",
    done: "Готово",
    loadLabel: "Тежина во килограми",
    repsLabel: "Повторувања",
    completeLabel: "Серијата е завршена",
    save: "Зачувај",
    saveSet: (n: number) => `Зачувај серија ${n}`,
    removeSet: (n: number) => `Отстрани серија ${n}`,
    addSet: "Додај серија",
    finishWorkout: "Заврши тренинг",
    recordsEyebrow: "Доказ за напредок",
    recordsIntro: "Се бројат само завршени серии. Ова се забележани рекорди, не проценети максимуми.",
    noRecordsTitle: "Вашите рекорди почнуваат со завршена работа",
    noRecordsBody: "Завршете тренинг и означете ги сериите како готови за да се пополни овој преглед.",
    personalBests: "Лични рекорди",
    heaviestLoad: "Најголема тежина",
    mostReps: "Најмногу повторувања",
    bestSetVolume: "Најдобар волумен во серија",
    bestSessionVolume: "Најдобар волумен во сесија",
    latestAchievement: (date: string) => `Последно достигнување · ${date}`,
    catalogueEyebrow: "Каталог на движења",
    catalogueIntro: "Јасни упатства, целни мускули и практични совети за опрема.",
  },
} as const;

export type FitnessCopy = (typeof fitnessContent)[Locale];

export function getFitnessCopy(locale: Locale): FitnessCopy {
  return fitnessContent[locale];
}
