"use client";
import { useMemo, useState } from "react";
import Link from "next/link";
import { Search, SlidersHorizontal } from "lucide-react";
import { equipmentOptions, exercises } from "@/features/fitness/catalogue";
export function ExerciseLibrary({ locale }: { locale: "en"|"mk" }) {
  const [query,setQuery]=useState(""); const [equipment,setEquipment]=useState("");
  const results=useMemo(()=>exercises.filter((exercise)=>{ const text=`${exercise.titleEn} ${exercise.titleMk} ${exercise.primaryMuscles.join(" ")}`.toLowerCase(); return text.includes(query.toLowerCase()) && (!equipment || exercise.equipment.includes(equipment)); }),[query,equipment]);
  const clear=()=>{setQuery("");setEquipment("");};
  return <div className="fitness-library"><div className="fitness-filter"><label><Search aria-hidden="true"/><span>{locale==="mk"?"Пребарај":"Search"}</span><input type="search" value={query} onChange={(event)=>setQuery(event.target.value)} placeholder={locale==="mk"?"Вежба или мускул":"Exercise or muscle"}/></label><label><SlidersHorizontal aria-hidden="true"/><span>{locale==="mk"?"Опрема":"Equipment"}</span><select aria-label="Equipment" value={equipment} onChange={(event)=>setEquipment(event.target.value)}><option value="">{locale==="mk"?"Сета опрема":"All equipment"}</option>{equipmentOptions.map((item)=><option key={item}>{item}</option>)}</select></label><button type="button" className="text-action" onClick={clear}>{locale==="mk"?"Исчисти филтри":"Clear filters"}</button></div>{results.length?<div className="exercise-grid">{results.map((exercise)=><Link className="exercise-card" href={`/exercises/${exercise.slug}`} key={exercise.slug}><span className={`movement-mark movement-${exercise.movementPattern}`}>{exercise.movementPattern}</span><div><p className="eyebrow">{exercise.exerciseType} · {exercise.difficulty}</p><h2>{locale==="mk"?exercise.titleMk:exercise.titleEn}</h2><p>{locale==="mk"?exercise.summaryMk:exercise.summaryEn}</p><ul className="tag-row">{exercise.equipment.map((item)=><li key={item}>{item}</li>)}</ul></div></Link>)}</div>:<div className="product-empty"><h2>{locale==="mk"?"Нема соодветни вежби.":"No exercises match those filters."}</h2><p>{locale==="mk"?"Исчистете ги филтрите или пробајте друг збор.":"Clear the filters or try a broader search."}</p><button type="button" onClick={clear}>Clear filters</button></div>}</div>;
}
