import type { CatalogueMedia } from "@/features/media/catalogue-media";

const repository = "https://github.com/wrkout/exercises.json";
const unlicense = `${repository}/blob/master/LICENSE.md`;

function wrkout(
  slug: string,
  sourceExercise: string,
  altEn: string,
  altMk: string,
  focalPoint: `${number}% ${number}%` = "50% 50%",
): CatalogueMedia {
  return {
    src: `/media/exercises/${slug}.webp`,
    alt: { en: altEn, mk: altMk },
    width: 800,
    height: 600,
    focalPoint,
    sourceName: "wrkout/exercises.json",
    sourceUrl: `${repository}/tree/master/exercises/${encodeURIComponent(sourceExercise)}`,
    licenseName: "Unlicense",
    licenseUrl: unlicense,
  };
}

function generated(
  slug: string,
  altEn: string,
  altMk: string,
  focalPoint: `${number}% ${number}%` = "50% 50%",
): CatalogueMedia {
  return {
    src: `/media/exercises/${slug}.webp`,
    alt: { en: altEn, mk: altMk },
    width: 800,
    height: 600,
    focalPoint,
    sourceName: "Original generated exercise demonstration",
    creator: "OpenAI image generation, directed and reviewed by B Fit & Healthy",
    licenseName: "Project-owned generated asset",
  };
}

export const exerciseMedia: Record<string, CatalogueMedia> = {
  "bodyweight-squat": wrkout("bodyweight-squat", "Bodyweight_Squat", "Athlete at the bottom of a bodyweight squat with feet grounded", "Спортист во долна положба на чучнување со сопствена тежина"),
  "goblet-squat": wrkout("goblet-squat", "Goblet_Squat", "Athlete holding a dumbbell at the chest during a goblet squat", "Спортист држи тег пред градите при пехар-чучнување"),
  "romanian-deadlift": wrkout("romanian-deadlift", "Romanian_Deadlift", "Athlete hinging at the hips during a Romanian deadlift", "Спортист се наведнува од колковите при романско мртво кревање"),
  "hip-bridge": wrkout("hip-bridge", "Butt_Lift_(Bridge)", "Athlete lifting the hips in a floor bridge", "Спортист ги подига колковите во мост на под"),
  "push-up": wrkout("push-up", "Pushups", "Athlete lowering with a straight body during a push-up", "Спортист се спушта со исправено тело при склек"),
  "dumbbell-bench-press": wrkout("dumbbell-bench-press", "Dumbbell_Bench_Press", "Athlete pressing two dumbbells while lying on a bench", "Спортист потиснува два тега лежејќи на клупа"),
  "overhead-press": generated("overhead-press", "Full-body view of an athlete pressing two dumbbells overhead from a grounded stance", "Целосен приказ на спортист што потиснува два тега над глава од стабилен став"),
  "one-arm-row": wrkout("one-arm-row", "One-Arm_Dumbbell_Row", "Athlete rowing one dumbbell with the other hand supported", "Спортист весла со еден тег со потпрена спротивна рака"),
  "seated-cable-row": wrkout("seated-cable-row", "Seated_Cable_Rows", "Athlete pulling a cable handle toward the torso while seated", "Спортист влече кабел кон трупот во седечка положба"),
  "lat-pulldown": generated("lat-pulldown", "Full-body view of an athlete pulling a cable bar to the upper chest with feet grounded", "Целосен приказ на спортист што влече кабелска шипка кон горниот дел од градите со стапалата на под"),
  "farmer-carry": wrkout("farmer-carry", "Farmer's_Walk", "Athlete walking upright with a heavy implement in each hand", "Спортист оди исправено носејќи товар во двете раце"),
  "dead-bug": wrkout("dead-bug", "Dead_Bug", "Athlete extending opposite limbs during a dead bug", "Спортист испружува спротивна рака и нога при мртва бубачка"),
  "side-plank": wrkout("side-plank", "Side_Bridge", "Athlete holding a straight side-plank position", "Спортист задржува права положба во страничен планк"),
  "thoracic-rotation": generated("thoracic-rotation", "Athlete rotating the upper back from a hands-and-knees position", "Спортист го ротира горниот дел од грбот од положба на дланки и колена"),
  "hip-flexor-mobility": wrkout("hip-flexor-mobility", "Kneeling_Hip_Flexor", "Athlete opening the front of the hip in a kneeling stretch", "Спортист го истегнува предниот дел на колкот во клечечка положба"),
  "reverse-lunge": wrkout("reverse-lunge", "Dumbbell_Rear_Lunge", "Athlete stepping backward into a controlled reverse lunge with dumbbells", "Спортист чекори наназад во контролирано обратно исчекорување со тегови"),
  "split-squat": wrkout("split-squat", "Split_Squat_with_Dumbbells", "Athlete lowering in a fixed split stance with dumbbells", "Спортист се спушта во фиксен расчекор со тегови"),
  "standing-calf-raise": wrkout("standing-calf-raise", "Standing_Calf_Raises", "Athlete rising onto the balls of the feet in a standing calf raise", "Спортист се подига на прсти при стоечко подигање за листови"),
  "incline-push-up": wrkout("incline-push-up", "Incline_Push-Up", "Athlete performing a push-up with hands on an elevated surface", "Спортист изведува склек со дланки на подигната површина"),
  "pike-push-up": generated("pike-push-up", "Athlete lowering the head between the hands in a pike push-up", "Спортист ја спушта главата меѓу дланките при пик-склек"),
  "lateral-raise": wrkout("lateral-raise", "Side_Lateral_Raise", "Athlete raising dumbbells to the sides with controlled arms", "Спортист контролирано подига тегови странично"),
  "biceps-curl": wrkout("biceps-curl", "Dumbbell_Bicep_Curl", "Athlete curling dumbbells without swinging the torso", "Спортист витка тегови без замавнување на трупот"),
  "overhead-triceps-extension": wrkout("overhead-triceps-extension", "Standing_Dumbbell_Triceps_Extension", "Athlete extending a dumbbell overhead with both hands", "Спортист испружува тег над глава со двете раце"),
  "band-pull-apart": wrkout("band-pull-apart", "Band_Pull_Apart", "Athlete pulling a resistance band apart at chest height", "Спортист ја растегнува еластичната лента во висина на градите"),
  "assisted-pull-up": generated("assisted-pull-up", "Athlete performing a pull-up with a band visibly attached from the bar to both feet", "Спортист изведува згиб со лента видливо прицврстена од вратилото до двете стапала"),
  "bird-dog": generated("bird-dog", "Athlete extending opposite arm and leg during a bird dog", "Спортист испружува спротивна рака и нога при вежбата птичје куче"),
  "front-plank": wrkout("front-plank", "Plank", "Athlete holding a straight forearm plank", "Спортист задржува права положба во планк на подлактици"),
  "pallof-press": generated("pallof-press", "Athlete standing perpendicular to a visible cable anchor during a Pallof press", "Спортист стои странично кон видлива кабелска котва при Палоф потисок"),
  "cat-cow": wrkout("cat-cow", "Cat_Stretch", "Athlete rounding the spine during a cat-cow mobility drill", "Спортист го заоблува 'рбетот при мобилност мачка-крава"),
  "ankle-rock": generated("ankle-rock", "Athlete driving the knee toward a wall while keeping the heel grounded", "Спортист го движи коленото кон ѕид додека петата останува на под"),
  "barbell-squat": wrkout("barbell-squat", "Barbell_Squat", "Athlete lowering into a back squat with a barbell", "Спортист се спушта во задно чучнување со шипка"),
  "front-squat": wrkout("front-squat", "Front_Squat_(Clean_Grip)", "Athlete holding a barbell on the front shoulders during a squat", "Спортист држи шипка на предните раменици при чучнување"),
  "step-up": wrkout("step-up", "Dumbbell_Step_Ups", "Athlete stepping onto a box while holding dumbbells", "Спортист се качува на кутија држејќи тегови"),
  "walking-lunge": wrkout("walking-lunge", "Bodyweight_Walking_Lunge", "Athlete moving forward through a bodyweight walking lunge", "Спортист се движи напред со исчекорување со сопствена тежина"),
  "leg-press": wrkout("leg-press", "Leg_Press", "Athlete pressing the platform of a leg-press machine", "Спортист ја турка платформата на машина за нозе"),
  "conventional-deadlift": wrkout("conventional-deadlift", "Barbell_Deadlift", "Athlete lifting a barbell from a conventional deadlift setup", "Спортист крева шипка од положба за класично мртво кревање"),
  "kettlebell-deadlift": generated("kettlebell-deadlift", "Athlete gripping one kettlebell in a neutral-spine deadlift setup", "Спортист држи кетлбел во положба за мртво кревање со неутрален грб"),
  "hip-thrust": wrkout("hip-thrust", "Barbell_Hip_Thrust", "Athlete extending the hips in a barbell hip thrust", "Спортист ги испружува колковите при потисок со шипка"),
  "hamstring-curl": wrkout("hamstring-curl", "Lying_Leg_Curls", "Athlete curling the legs on a lying hamstring-curl machine", "Спортист ги витка нозете на лежечка машина за задни ложи"),
  "barbell-bench-press": wrkout("barbell-bench-press", "Barbell_Bench_Press_-_Medium_Grip", "Athlete pressing a barbell from a flat bench", "Спортист потиснува шипка лежејќи на рамна клупа"),
  "cable-chest-press": generated("cable-chest-press", "Full-body view of an athlete pressing two handles forward from visible cable columns", "Целосен приказ на спортист што турка две рачки напред од видливи кабелски столбови"),
  "chest-fly": wrkout("chest-fly", "Dumbbell_Flyes", "Athlete bringing dumbbells together in a bench chest fly", "Спортист ги приближува теговите при разлетување за гради"),
  "pull-up": wrkout("pull-up", "Pullups", "Athlete pulling the body upward from a bar", "Спортист го повлекува телото нагоре на вратило"),
  "chest-supported-row": wrkout("chest-supported-row", "Dumbbell_Incline_Row", "Athlete rowing dumbbells with the chest supported on an incline bench", "Спортист весла со тегови со гради потпрени на накосена клупа"),
  "face-pull": generated("face-pull", "Full-body view of an athlete pulling a rope toward the face from a visible cable anchor", "Целосен приказ на спортист што влече јаже кон лицето од видлива кабелска котва"),
  "landmine-press": wrkout("landmine-press", "Landmine_Linear_Jammer", "Athlete pressing the anchored end of a barbell forward and upward", "Спортист го турка прицврстениот крај на шипката напред и нагоре"),
  "machine-shoulder-press": wrkout("machine-shoulder-press", "Machine_Shoulder_(Military)_Press", "Athlete pressing overhead on a shoulder-press machine", "Спортист потиснува над глава на машина за раменици"),
  "rear-delt-fly": wrkout("rear-delt-fly", "Bent_Over_Dumbbell_Rear_Delt_Raise_With_Head_On_Bench", "Athlete raising dumbbells outward for a supported rear-delt fly", "Спортист ги подига теговите нанадвор за потпрено разлетување за задно рамо"),
  "hammer-curl": wrkout("hammer-curl", "Hammer_Curls", "Athlete curling dumbbells with palms facing inward", "Спортист витка тегови со дланките свртени навнатре"),
  "cable-triceps-press-down": wrkout("cable-triceps-press-down", "Triceps_Pushdown_-_Rope_Attachment", "Athlete pressing a cable rope downward with elbows close", "Спортист го турка кабелското јаже надолу со лакти покрај телото"),
  "kettlebell-carry": generated("kettlebell-carry", "Athlete walking upright with one kettlebell in each hand", "Спортист оди исправено со по еден кетлбел во секоја рака"),
  "suitcase-carry": generated("suitcase-carry", "Athlete walking upright with one kettlebell at the side", "Спортист оди исправено со еден кетлбел покрај телото"),
  "hollow-hold": generated("hollow-hold", "Athlete holding arms and legs above the floor in a hollow-body position", "Спортист ги задржува рацете и нозете над подот во шуплива положба"),
  "reverse-crunch": wrkout("reverse-crunch", "Reverse_Crunch", "Athlete curling the pelvis upward in a reverse crunch", "Спортист ја подвиткува карлицата нагоре при обратно стомачно свиткување"),
  "cable-chop": wrkout("cable-chop", "Standing_Cable_Wood_Chop", "Athlete guiding a cable diagonally across the torso", "Спортист го води кабелот дијагонално преку трупот"),
  "shoulder-wall-slide": generated("shoulder-wall-slide", "Athlete holding forearms against a wall for a shoulder wall slide", "Спортист ги држи подлактиците на ѕид при лизгање за раменици"),
  "90-90-hip-switch": generated("90-90-hip-switch", "Athlete seated with both legs bent in a 90/90 hip position", "Спортист седи со двете нозе свиткани во положба 90/90 за колкови"),
  "calf-mobility": wrkout("calf-mobility", "Calf_Stretch_Hands_Against_Wall", "Athlete stretching the calf against a wall with the heel grounded", "Спортист го истегнува листот на ѕид со петата на под"),
  "childs-pose-reach": generated("childs-pose-reach", "Athlete reaching both arms forward in child's pose", "Спортист ги испружува двете раце напред во детска положба"),
  "deep-squat-hold": wrkout("deep-squat-hold", "Bodyweight_Squat", "Athlete holding the bottom of a deep bodyweight squat", "Спортист ја задржува долната положба на длабоко чучнување"),
  "barbell-row": wrkout("barbell-row", "Bent_Over_Barbell_Row", "Athlete hinging forward to row a loaded barbell into the torso", "Спортист наведнат напред весла оптоварена шипка кон трупот"),
  "v-bar-pulldown": wrkout("v-bar-pulldown", "V-Bar_Pulldown", "Athlete pulling a close V-bar attachment down to the chest", "Спортист влече тесна В-рачка надолу кон градите"),
  "dumbbell-pullover": wrkout("dumbbell-pullover", "Bent-Arm_Dumbbell_Pullover", "Athlete lowering a dumbbell overhead in an arc while lying on a bench", "Спортист спушта тег над глава во лак лежејќи на клупа"),
  "band-chest-press": wrkout("band-chest-press", "Bench_Press_-_With_Bands", "Athlete pressing a barbell fitted with resistance bands from a bench", "Спортист потиснува шипка со прицврстени еластични ленти лежејќи на клупа"),
  "triceps-kickback": wrkout("triceps-kickback", "Tricep_Dumbbell_Kickback", "Athlete extending a dumbbell backward behind a bent torso", "Спортист испружува тег наназад зад наведнат труп"),
  "lying-triceps-extension": wrkout("lying-triceps-extension", "Lying_Triceps_Press", "Athlete lowering a dumbbell toward the forehead while lying on a bench", "Спортист спушта тег кон челото лежејќи на клупа"),
  "cable-rope-overhead-extension": wrkout("cable-rope-overhead-extension", "Cable_Rope_Overhead_Triceps_Extension", "Athlete extending a cable rope overhead to load the triceps", "Спортист испружува кабелско јаже над глава за да го оптовари трицепсот"),
  "reverse-curl": wrkout("reverse-curl", "Standing_Dumbbell_Reverse_Curl", "Athlete curling dumbbells with an overhand, palms-down grip", "Спортист витка тегови со надворешен фат, дланки надолу"),
  "barbell-overhead-press": wrkout("barbell-overhead-press", "Standing_Military_Press", "Athlete pressing a barbell from the shoulders to overhead lockout", "Спортист потиснува шипка од рамениците до целосно испружување над глава"),
  "upright-row": wrkout("upright-row", "Standing_Dumbbell_Upright_Row", "Athlete pulling dumbbells vertically along the body toward the chin", "Спортист влече тегови вертикално долж телото кон брадата"),
  "arnold-press": wrkout("arnold-press", "Arnold_Dumbbell_Press", "Athlete rotating two dumbbells while pressing overhead", "Спортист ротира два тега додека потиснува над глава"),
  "ab-wheel-rollout": wrkout("ab-wheel-rollout", "Barbell_Ab_Rollout_-_On_Knees", "Athlete rolling a loaded bar forward from a kneeling, braced position", "Спортист ролја оптоварена шипка напред од клечечка, стабилна положба"),
  "t-jacks": wrkout("t-jacks", "Star_Jump", "Athlete jumping with arms sweeping overhead into a star shape", "Спортист скока со рацете во замав над глава во форма на ѕвезда"),
  "bear-crawl": wrkout("bear-crawl", "Bear_Crawl_Sled_Drags", "Athlete crawling forward on hands and feet with hips low", "Спортист лази напред на дланки и стапала со ниски колкови"),
  "lateral-shuffle": wrkout("lateral-shuffle", "Side_to_Side_Box_Shuffle", "Athlete shuffling sideways in a low athletic stance", "Спортист лизга странично во ниска атлетска положба"),
  "forward-lunge-twist": wrkout("forward-lunge-twist", "Crossover_Reverse_Lunge", "Athlete stepping into a lunge while rotating the trunk", "Спортист чекори во исчекор додека го ротира трупот"),
  "basic-burpee": wrkout("basic-burpee", "Knee_Tuck_Jump", "Athlete in mid-air during an explosive full-body jump", "Спортист во воздух при експлозивен скок на целото тело"),
  "a-skips": wrkout("a-skips", "Fast_Skipping", "Athlete driving one knee up in a fast skipping cadence", "Спортист подига едно колено нагоре во брз ритам на прескокнување"),
  "run-lunge-squat": wrkout("run-lunge-squat", "Bodyweight_Walking_Lunge", "Athlete moving through a bodyweight lunge as part of a combo drill", "Спортист изведува исчекор со сопствена тежина како дел од комбинирана вежба"),
  "sprint-in-place": wrkout("sprint-in-place", "Rope_Jumping", "Athlete driving the knees at a fast cadence without traveling forward", "Спортист брзо ги движи колената без движење напред"),
  "mountain-climbers": wrkout("mountain-climbers", "Mountain_Climbers", "Athlete driving one knee toward the chest from a plank position", "Спортист носи едно колено кон градите од положба на планк"),
  "high-feet": wrkout("high-feet", "Fast_Skipping", "Athlete taking fast, small steps with feet staying under the hips", "Спортист прави брзи, ситни чекори со стапалата под колковите"),
  "gorilla-crawl": wrkout("gorilla-crawl", "Bear_Crawl_Sled_Drags", "Athlete moving forward from a low squat with hands planted between the feet", "Спортист се движи напред од ниско чучнување со дланки меѓу стапалата"),
  "spartan-squat": wrkout("spartan-squat", "Freehand_Jump_Squat", "Athlete finishing an explosive bodyweight squat with a small jump", "Спортист завршува експлозивно чучнување со мал скок"),
  "star-crunch": wrkout("star-crunch", "Tuck_Crunch", "Athlete curling the limbs together toward the center of the body", "Спортист ги свиткува екстремитетите кон центарот на телото"),
  "plank-to-squat": wrkout("plank-to-squat", "Plank", "Athlete holding a plank position before walking the feet toward the hands", "Спортист држи планк пред да ги придвижи стапалата кон дланките"),
  "spider-crawl": wrkout("spider-crawl", "Spider_Crawl", "Athlete crawling forward bringing the knee outside the same-side elbow", "Спортист лази напред носејќи го коленото надвор од истостраниот лакт"),
  "skip-flys": wrkout("skip-flys", "Star_Jump", "Athlete skipping with a wide overhead arm sweep", "Спортист прескокнува со широк замав на рацете над глава"),
  "cross-climbers": wrkout("cross-climbers", "Mountain_Climbers", "Athlete driving a knee across the body from a plank position", "Спортист носи колено преку телото од положба на планк"),
  "fast-feet-low-plank": wrkout("fast-feet-low-plank", "Plank", "Athlete holding a low plank while tapping the feet quickly", "Спортист држи низок планк додека брзо ги допира стапалата"),
  "low-plank-side-knee": wrkout("low-plank-side-knee", "Plank", "Athlete holding a low plank while drawing a knee out to the side", "Спортист држи низок планк додека повлекува колено странично"),
  "plank-party": wrkout("plank-party", "Plank", "Athlete moving between a forearm plank and a straight-arm plank", "Спортист се движи помеѓу планк на подлактици и планк на испружени раце"),
  "spin-burpee": wrkout("spin-burpee", "Knee_Tuck_Jump", "Athlete in mid-air during an explosive full-body jump with a turn", "Спортист во воздух при експлозивен скок на целото тело со вртење"),
  "bulgarian-split-squat": wrkout("bulgarian-split-squat", "Suspended_Split_Squat", "Athlete lowering into a split squat with the rear foot elevated", "Спортист се спушта во split чучнување со задната нога кренато"),
  "sumo-squat": wrkout("sumo-squat", "Plie_Dumbbell_Squat", "Athlete squatting with a wide stance and toes turned outward", "Спортист чучнува со широк став и стапала свртени нанадвор"),
  "clean-and-press": wrkout("clean-and-press", "Clean_and_Press", "Athlete pressing a barbell overhead after pulling it to the shoulders", "Спортист потиснува шипка над глава откако ја крена до рамениците"),
  "t-bar-row": wrkout("t-bar-row", "T-Bar_Row_with_Handle", "Athlete rowing a T-bar handle while hinged forward at the hips", "Спортист весла Т-бар рачка додека е наведнат напред од колковите"),
  "zottman-curl": wrkout("zottman-curl", "Zottman_Curl", "Athlete curling dumbbells with a grip rotation between the up and down phase", "Спортист витка тегови со ротација на фатот меѓу горната и долната фаза"),
};
