export type WorkoutGoal = "strength" | "mobility" | "conditioning";

export type WorkoutPrescription = {
  exerciseSlug: string;
  sets: number;
  repMin: number | null;
  repMax: number | null;
  durationSeconds: number | null;
  restSeconds: number;
};

export type WorkoutIdea = {
  slug: string;
  title: string;
  summary: string;
  goal: WorkoutGoal;
  durationMinutes: number;
  level: "beginner" | "intermediate" | "advanced";
  equipment: string[];
  isFullBody: boolean;
  exercises: WorkoutPrescription[];
};

const reps = (
  exerciseSlug: string,
  sets = 3,
  repMin = 8,
  repMax = 12,
  restSeconds = 90,
): WorkoutPrescription => ({
  exerciseSlug,
  sets,
  repMin,
  repMax,
  durationSeconds: null,
  restSeconds,
});

const timed = (
  exerciseSlug: string,
  durationSeconds = 40,
  restSeconds = 20,
): WorkoutPrescription => ({
  exerciseSlug,
  sets: 1,
  repMin: null,
  repMax: null,
  durationSeconds,
  restSeconds,
});

export const workoutIdeas: WorkoutIdea[] = [
  {
    slug: "bodyweight-foundations",
    title: "Bodyweight foundations",
    summary: "A calm full-body strength session for learning the core movement patterns.",
    goal: "strength",
    durationMinutes: 45,
    level: "beginner",
    equipment: ["Bodyweight"],
    isFullBody: true,
    exercises: [
      reps("bodyweight-squat", 3, 10, 15, 60),
      reps("reverse-lunge", 3, 8, 12, 60),
      reps("hip-bridge", 3, 12, 15, 60),
      reps("push-up", 3, 6, 12, 75),
      reps("incline-push-up", 2, 8, 12, 60),
      reps("pike-push-up", 2, 6, 10, 75),
      reps("bird-dog", 2, 8, 10, 30),
      reps("dead-bug", 2, 8, 10, 30),
      timed("side-plank", 30, 30),
      reps("standing-calf-raise", 3, 12, 20, 45),
    ],
  },
  {
    slug: "lower-body-control",
    title: "Lower-body control",
    summary: "Build confident squatting, hinging and single-session trunk control.",
    goal: "strength",
    durationMinutes: 30,
    level: "beginner",
    equipment: ["Bodyweight"],
    isFullBody: false,
    exercises: [
      reps("bodyweight-squat", 3, 10, 15, 60),
      reps("hip-bridge", 3, 12, 15, 60),
      timed("side-plank", 30, 30),
    ],
  },
  {
    slug: "dumbbell-full-body",
    title: "Dumbbell full body",
    summary: "A balanced push, pull, squat and carry session with minimal equipment.",
    goal: "strength",
    durationMinutes: 60,
    level: "beginner",
    equipment: ["Dumbbells"],
    isFullBody: true,
    exercises: [
      reps("goblet-squat", 3, 8, 12, 90),
      reps("romanian-deadlift", 3, 8, 12, 90),
      reps("split-squat", 3, 8, 10, 75),
      reps("dumbbell-bench-press", 3, 8, 12, 90),
      reps("one-arm-row", 3, 8, 12, 75),
      reps("overhead-press", 3, 8, 12, 90),
      reps("lateral-raise", 2, 12, 15, 60),
      reps("biceps-curl", 2, 10, 15, 60),
      reps("overhead-triceps-extension", 2, 10, 15, 60),
      timed("farmer-carry", 40, 60),
    ],
  },
  {
    slug: "posterior-chain-builder",
    title: "Posterior-chain builder",
    summary: "Train the hips, hamstrings, glutes and upper back with controlled loading.",
    goal: "strength",
    durationMinutes: 38,
    level: "intermediate",
    equipment: ["Dumbbells"],
    isFullBody: false,
    exercises: [
      reps("romanian-deadlift", 4, 6, 10, 120),
      reps("hip-bridge", 3, 10, 15, 75),
      reps("one-arm-row", 3, 8, 12, 90),
      reps("dead-bug", 3, 8, 10, 45),
    ],
  },
  {
    slug: "upper-body-basics",
    title: "Upper-body basics",
    summary: "Straightforward pushing and pulling with scalable beginner movements.",
    goal: "strength",
    durationMinutes: 28,
    level: "beginner",
    equipment: ["Bodyweight", "Dumbbell"],
    isFullBody: false,
    exercises: [
      reps("push-up", 3, 6, 12, 75),
      reps("one-arm-row", 3, 8, 12, 75),
      timed("side-plank", 30, 30),
    ],
  },
  {
    slug: "gym-strength-starter",
    title: "Gym strength starter",
    summary: "A first gym routine using stable, adjustable resistance exercises.",
    goal: "strength",
    durationMinutes: 45,
    level: "beginner",
    equipment: ["Cable", "Dumbbells"],
    isFullBody: false,
    exercises: [
      reps("goblet-squat"),
      reps("seated-cable-row"),
      reps("overhead-press"),
      reps("lat-pulldown"),
    ],
  },
  {
    slug: "desk-reset",
    title: "Desk-day reset",
    summary: "Gentle rotation and hip work to restore comfortable movement.",
    goal: "mobility",
    durationMinutes: 12,
    level: "beginner",
    equipment: ["Bodyweight"],
    isFullBody: false,
    exercises: [
      timed("thoracic-rotation"),
      timed("hip-flexor-mobility"),
      timed("dead-bug"),
    ],
  },
  {
    slug: "hips-and-spine",
    title: "Hips and spine mobility",
    summary: "A short mobility flow focused on hips, trunk control and upper-back rotation.",
    goal: "mobility",
    durationMinutes: 18,
    level: "beginner",
    equipment: ["Bodyweight"],
    isFullBody: false,
    exercises: [
      timed("hip-flexor-mobility", 45, 15),
      timed("thoracic-rotation", 45, 15),
      timed("hip-bridge", 40, 20),
    ],
  },
  {
    slug: "warm-up-flow",
    title: "Full-body warm-up flow",
    summary: "Prepare the major joints and movement patterns before a main workout.",
    goal: "mobility",
    durationMinutes: 18,
    level: "beginner",
    equipment: ["Bodyweight"],
    isFullBody: true,
    exercises: [
      timed("cat-cow"),
      timed("thoracic-rotation"),
      timed("hip-flexor-mobility"),
      timed("ankle-rock"),
      timed("bodyweight-squat"),
      timed("reverse-lunge"),
      timed("hip-bridge"),
      timed("incline-push-up"),
      timed("bird-dog"),
      timed("dead-bug"),
    ],
  },
  {
    slug: "steady-circuit",
    title: "Steady full-body circuit",
    summary: "Alternate simple movements at a sustainable pace without chasing exhaustion.",
    goal: "conditioning",
    durationMinutes: 35,
    level: "beginner",
    equipment: ["Bodyweight"],
    isFullBody: true,
    exercises: [
      reps("bodyweight-squat", 3, 12, 15, 30),
      reps("reverse-lunge", 3, 8, 12, 30),
      reps("hip-bridge", 3, 12, 15, 30),
      reps("push-up", 3, 6, 12, 30),
      reps("pike-push-up", 3, 6, 10, 30),
      reps("standing-calf-raise", 3, 15, 20, 30),
      timed("bird-dog", 40, 20),
      timed("dead-bug", 40, 20),
      timed("front-plank", 30, 30),
      timed("side-plank", 30, 30),
    ],
  },
  {
    slug: "carry-and-core",
    title: "Carry and core circuit",
    summary: "Short work blocks for posture, grip and trunk endurance.",
    goal: "conditioning",
    durationMinutes: 24,
    level: "intermediate",
    equipment: ["Dumbbells"],
    isFullBody: false,
    exercises: [
      timed("farmer-carry", 45, 45),
      reps("goblet-squat", 3, 10, 15, 45),
      timed("side-plank", 30, 30),
    ],
  },
  {
    slug: "strength-density",
    title: "Strength density session",
    summary: "A compact dumbbell circuit that keeps quality high and rest intentional.",
    goal: "conditioning",
    durationMinutes: 30,
    level: "intermediate",
    equipment: ["Dumbbells"],
    isFullBody: false,
    exercises: [
      reps("goblet-squat", 4, 8, 10, 45),
      reps("one-arm-row", 4, 8, 10, 45),
      reps("overhead-press", 4, 8, 10, 45),
      timed("farmer-carry", 40, 45),
    ],
  },
  {
    slug: "barbell-strength-essentials",
    title: "Barbell strength essentials",
    summary: "Build foundational strength with the big barbell lifts and a stable back-loaded squat.",
    goal: "strength",
    durationMinutes: 50,
    level: "advanced",
    equipment: ["Barbell", "Bench"],
    isFullBody: false,
    exercises: [
      reps("barbell-squat", 4, 5, 8, 120),
      reps("conventional-deadlift", 3, 5, 8, 150),
      reps("barbell-bench-press", 4, 6, 10, 120),
      reps("pull-up", 3, 5, 10, 120),
    ],
  },
  {
    slug: "front-squat-and-press",
    title: "Front squat and press",
    summary: "Pair a front-loaded squat with an angled overhead press for legs and shoulders.",
    goal: "strength",
    durationMinutes: 35,
    level: "intermediate",
    equipment: ["Barbell"],
    isFullBody: false,
    exercises: [
      reps("front-squat", 4, 6, 10, 120),
      reps("landmine-press", 3, 8, 12, 90),
      reps("split-squat", 3, 8, 10, 75),
    ],
  },
  {
    slug: "kettlebell-conditioning",
    title: "Kettlebell conditioning",
    summary: "Combine a hip hinge, a loaded carry, and a squat for a compact kettlebell session.",
    goal: "conditioning",
    durationMinutes: 25,
    level: "intermediate",
    equipment: ["Kettlebell"],
    isFullBody: false,
    exercises: [
      reps("kettlebell-deadlift", 4, 8, 12, 60),
      timed("kettlebell-carry", 45, 30),
      reps("goblet-squat", 3, 10, 15, 45),
    ],
  },
  {
    slug: "pull-focused-upper-body",
    title: "Pull-focused upper body",
    summary: "Prioritize vertical and horizontal pulling for a stronger, more balanced upper back.",
    goal: "strength",
    durationMinutes: 30,
    level: "intermediate",
    equipment: ["Bodyweight", "Band", "Cable", "Dumbbells", "Bench"],
    isFullBody: false,
    exercises: [
      reps("assisted-pull-up", 3, 5, 10, 90),
      reps("lat-pulldown", 3, 8, 12, 90),
      reps("face-pull", 3, 12, 15, 60),
      reps("chest-supported-row", 3, 8, 12, 75),
    ],
  },
  {
    slug: "push-day-machines",
    title: "Push day, machines",
    summary: "A guided, joint-friendly pushing session using machines and cables.",
    goal: "strength",
    durationMinutes: 30,
    level: "beginner",
    equipment: ["Machine", "Cable", "Dumbbells", "Bench"],
    isFullBody: false,
    exercises: [
      reps("machine-shoulder-press", 3, 8, 12, 90),
      reps("cable-chest-press", 3, 8, 12, 90),
      reps("chest-fly", 2, 10, 15, 60),
      reps("overhead-triceps-extension", 2, 10, 15, 60),
    ],
  },
  {
    slug: "leg-day-gym",
    title: "Leg day at the gym",
    summary: "Combine a machine press, a barbell squat, and hamstring work for complete leg training.",
    goal: "strength",
    durationMinutes: 40,
    level: "intermediate",
    equipment: ["Machine", "Barbell"],
    isFullBody: false,
    exercises: [
      reps("leg-press", 4, 8, 12, 90),
      reps("barbell-squat", 3, 6, 10, 120),
      reps("hamstring-curl", 3, 10, 15, 75),
      reps("standing-calf-raise", 3, 12, 20, 45),
    ],
  },
  {
    slug: "hip-thrust-glute-focus",
    title: "Hip thrust glute focus",
    summary: "Target the glutes and hamstrings with a hip thrust, a hinge, and a walking lunge.",
    goal: "strength",
    durationMinutes: 25,
    level: "intermediate",
    equipment: ["Barbell", "Bench", "Dumbbells"],
    isFullBody: false,
    exercises: [
      reps("hip-thrust", 4, 8, 12, 90),
      reps("romanian-deadlift", 3, 8, 12, 90),
      reps("walking-lunge", 3, 10, 12, 60),
    ],
  },
  {
    slug: "core-stability-circuit",
    title: "Core stability circuit",
    summary: "Train anti-extension, anti-rotation, and flexion control in one short circuit.",
    goal: "conditioning",
    durationMinutes: 15,
    level: "beginner",
    equipment: ["Bodyweight", "Band"],
    isFullBody: false,
    exercises: [
      timed("hollow-hold", 30, 20),
      reps("pallof-press", 3, 10, 12, 30),
      reps("reverse-crunch", 2, 12, 15, 30),
      timed("dead-bug", 40, 20),
      timed("front-plank", 30, 30),
    ],
  },
  {
    slug: "band-and-bodyweight-upper",
    title: "Band and bodyweight upper body",
    summary: "A minimal-equipment pushing and pulling session using bands and bodyweight.",
    goal: "strength",
    durationMinutes: 25,
    level: "beginner",
    equipment: ["Band", "Bodyweight", "Dumbbells"],
    isFullBody: false,
    exercises: [
      reps("band-pull-apart", 3, 15, 20, 45),
      reps("push-up", 3, 8, 12, 75),
      reps("incline-push-up", 2, 8, 12, 60),
      reps("rear-delt-fly", 2, 12, 15, 60),
    ],
  },
  {
    slug: "step-and-carry-conditioning",
    title: "Step and carry conditioning",
    summary: "Build single-leg strength and grip endurance with steps and loaded carries.",
    goal: "conditioning",
    durationMinutes: 22,
    level: "intermediate",
    equipment: ["Dumbbells", "Kettlebell"],
    isFullBody: false,
    exercises: [
      reps("step-up", 3, 10, 12, 45),
      timed("suitcase-carry", 40, 40),
      reps("walking-lunge", 3, 10, 12, 45),
    ],
  },
  {
    slug: "advanced-full-body-strength",
    title: "Advanced full-body strength",
    summary: "A demanding session that pairs heavy compound lifts with a vertical pull.",
    goal: "strength",
    durationMinutes: 55,
    level: "advanced",
    equipment: ["Barbell", "Dumbbells", "Bench", "Bodyweight"],
    isFullBody: false,
    exercises: [
      reps("conventional-deadlift", 4, 4, 6, 150),
      reps("barbell-bench-press", 4, 5, 8, 120),
      reps("barbell-squat", 4, 5, 8, 120),
      reps("pull-up", 4, 5, 8, 120),
      reps("overhead-press", 3, 6, 10, 90),
    ],
  },
  {
    slug: "mobility-flow-morning",
    title: "Morning mobility flow",
    summary: "A short flow to open the spine, hips, and ankles before the day starts.",
    goal: "mobility",
    durationMinutes: 10,
    level: "beginner",
    equipment: ["Bodyweight"],
    isFullBody: false,
    exercises: [
      timed("cat-cow"),
      timed("childs-pose-reach"),
      timed("90-90-hip-switch"),
      timed("calf-mobility"),
    ],
  },
  {
    slug: "deep-squat-hip-mobility",
    title: "Deep squat and hip mobility",
    summary: "Explore comfortable squat depth and hip range with supported holds.",
    goal: "mobility",
    durationMinutes: 14,
    level: "beginner",
    equipment: ["Bodyweight"],
    isFullBody: false,
    exercises: [
      timed("deep-squat-hold", 30, 20),
      timed("hip-flexor-mobility"),
      timed("90-90-hip-switch"),
      timed("ankle-rock"),
    ],
  },
  {
    slug: "shoulder-health-flow",
    title: "Shoulder health flow",
    summary: "Combine wall-guided motion and light band work to support comfortable overhead reach.",
    goal: "mobility",
    durationMinutes: 12,
    level: "beginner",
    equipment: ["Bodyweight", "Band"],
    isFullBody: false,
    exercises: [
      timed("shoulder-wall-slide"),
      timed("thoracic-rotation"),
      reps("band-pull-apart", 2, 15, 20, 30),
      timed("childs-pose-reach"),
    ],
  },
  {
    slug: "quick-home-circuit",
    title: "Quick home circuit",
    summary: "A short, equipment-free circuit for days when time is tight.",
    goal: "conditioning",
    durationMinutes: 18,
    level: "beginner",
    equipment: ["Bodyweight"],
    isFullBody: false,
    exercises: [
      reps("reverse-lunge", 3, 10, 12, 30),
      reps("push-up", 3, 8, 12, 30),
      reps("hip-bridge", 3, 12, 15, 30),
      timed("hollow-hold", 20, 20),
      timed("bird-dog", 30, 20),
    ],
  },
  {
    slug: "circuit-chest-triceps",
    title: "Circuit: chest and triceps",
    summary: "A four-to-five-set circuit pairing pressing and fly movements with triceps isolation.",
    goal: "strength",
    durationMinutes: 50,
    level: "intermediate",
    equipment: ["Bodyweight", "Dumbbells", "Band"],
    isFullBody: false,
    exercises: [
      reps("push-up", 5, 10, 12, 75),
      reps("chest-fly", 4, 10, 12, 75),
      reps("band-chest-press", 4, 10, 12, 75),
      reps("dumbbell-bench-press", 4, 10, 12, 90),
      reps("overhead-triceps-extension", 4, 10, 12, 60),
      reps("triceps-kickback", 4, 10, 12, 60),
    ],
  },
  {
    slug: "circuit-back-biceps",
    title: "Circuit: back and biceps",
    summary: "Vertical and horizontal pulling paired with direct biceps work in a steady circuit.",
    goal: "strength",
    durationMinutes: 50,
    level: "intermediate",
    equipment: ["Cable", "Barbell", "Dumbbells"],
    isFullBody: false,
    exercises: [
      reps("lat-pulldown", 4, 10, 12, 90),
      reps("barbell-row", 4, 10, 12, 90),
      reps("v-bar-pulldown", 4, 10, 12, 90),
      reps("one-arm-row", 4, 10, 12, 75),
      reps("biceps-curl", 4, 10, 12, 60),
      reps("reverse-curl", 4, 10, 12, 60),
    ],
  },
  {
    slug: "circuit-shoulders-arms",
    title: "Circuit: shoulders and arms",
    summary: "A high-volume circuit covering every deltoid head plus biceps and triceps finishers.",
    goal: "strength",
    durationMinutes: 55,
    level: "intermediate",
    equipment: ["Dumbbells"],
    isFullBody: false,
    exercises: [
      reps("lateral-raise", 4, 10, 12, 60),
      reps("biceps-curl", 4, 10, 12, 60),
      reps("triceps-kickback", 4, 10, 12, 60),
      reps("rear-delt-fly", 4, 10, 12, 60),
      reps("hammer-curl", 4, 10, 12, 60),
      reps("lying-triceps-extension", 4, 10, 12, 60),
      reps("overhead-press", 4, 10, 12, 90),
      reps("overhead-triceps-extension", 4, 10, 12, 60),
    ],
  },
  {
    slug: "circuit-chest-back",
    title: "Circuit: chest and back (old school)",
    summary: "Alternate pressing and pulling patterns set for set, old-school bodybuilding style.",
    goal: "strength",
    durationMinutes: 55,
    level: "intermediate",
    equipment: ["Bodyweight", "Cable", "Barbell", "Band", "Dumbbell", "Bench"],
    isFullBody: false,
    exercises: [
      reps("push-up", 5, 10, 12, 75),
      reps("lat-pulldown", 4, 10, 12, 90),
      reps("incline-push-up", 4, 10, 12, 75),
      reps("barbell-row", 4, 10, 12, 90),
      reps("band-chest-press", 4, 10, 12, 75),
      reps("v-bar-pulldown", 4, 10, 12, 90),
      reps("cable-chest-press", 4, 10, 12, 90),
      reps("dumbbell-pullover", 4, 10, 12, 75),
    ],
  },
  {
    slug: "circuit-shoulders",
    title: "Circuit: shoulders (old school)",
    summary: "Six-movement shoulder circuit covering pressing, raises, and rotational pulling.",
    goal: "strength",
    durationMinutes: 45,
    level: "intermediate",
    equipment: ["Dumbbells", "Barbell"],
    isFullBody: false,
    exercises: [
      reps("lateral-raise", 4, 10, 12, 60),
      reps("barbell-overhead-press", 4, 10, 12, 90),
      reps("ab-wheel-rollout", 4, 10, 12, 60),
      reps("upright-row", 4, 10, 12, 60),
      reps("rear-delt-fly", 4, 10, 12, 60),
      reps("arnold-press", 4, 10, 12, 90),
    ],
  },
  {
    slug: "circuit-arms",
    title: "Circuit: arms (old school)",
    summary: "A focused biceps-and-triceps circuit combining free weights and cable attachments.",
    goal: "strength",
    durationMinutes: 40,
    level: "intermediate",
    equipment: ["Dumbbells", "Cable"],
    isFullBody: false,
    exercises: [
      reps("biceps-curl", 4, 10, 12, 60),
      reps("triceps-kickback", 4, 10, 12, 60),
      reps("hammer-curl", 4, 10, 12, 60),
      reps("cable-rope-overhead-extension", 4, 10, 12, 60),
      reps("reverse-curl", 4, 10, 12, 60),
      reps("cable-triceps-press-down", 4, 10, 12, 60),
    ],
  },
  {
    slug: "cardio-circuit-one",
    title: "Cardio circuit I",
    summary: "Three descending-and-ascending rounds of jumps, crawls, and lunges for a fast heart-rate finisher.",
    goal: "conditioning",
    durationMinutes: 25,
    level: "advanced",
    equipment: ["Bodyweight"],
    isFullBody: false,
    exercises: [
      reps("t-jacks", 3, 30, 50, 30),
      reps("bear-crawl", 3, 20, 30, 30),
      reps("lateral-shuffle", 3, 20, 30, 30),
      reps("forward-lunge-twist", 3, 10, 20, 30),
      reps("basic-burpee", 3, 15, 25, 30),
      reps("a-skips", 3, 30, 50, 30),
      reps("run-lunge-squat", 3, 30, 50, 30),
    ],
  },
  {
    slug: "cardio-circuit-two",
    title: "Cardio circuit II",
    summary: "A crawling and squatting circuit that alternates sprint cadence with core-focused finishers.",
    goal: "conditioning",
    durationMinutes: 25,
    level: "advanced",
    equipment: ["Bodyweight"],
    isFullBody: false,
    exercises: [
      reps("sprint-in-place", 3, 40, 60, 30),
      reps("mountain-climbers", 3, 30, 50, 30),
      reps("high-feet", 3, 30, 50, 30),
      reps("gorilla-crawl", 3, 16, 26, 30),
      reps("spartan-squat", 3, 30, 50, 30),
      reps("star-crunch", 3, 15, 25, 30),
      reps("plank-to-squat", 3, 15, 25, 30),
    ],
  },
  {
    slug: "cardio-circuit-three",
    title: "Cardio circuit III",
    summary: "A plank-heavy circuit combining crawls, cross-body climbers, and rapid foot-speed work.",
    goal: "conditioning",
    durationMinutes: 25,
    level: "advanced",
    equipment: ["Bodyweight"],
    isFullBody: false,
    exercises: [
      reps("spider-crawl", 3, 10, 15, 30),
      reps("skip-flys", 3, 30, 50, 30),
      reps("cross-climbers", 3, 30, 40, 30),
      reps("fast-feet-low-plank", 3, 8, 15, 30),
      reps("low-plank-side-knee", 3, 20, 30, 30),
      reps("plank-party", 3, 10, 20, 30),
      reps("spin-burpee", 3, 12, 20, 30),
    ],
  },
  {
    slug: "cardio-circuit-mix",
    title: "Cardio circuit: mix of all",
    summary: "A finisher that samples the toughest movements from every cardio circuit in one session.",
    goal: "conditioning",
    durationMinutes: 25,
    level: "advanced",
    equipment: ["Bodyweight"],
    isFullBody: false,
    exercises: [
      reps("t-jacks", 3, 30, 50, 30),
      reps("mountain-climbers", 3, 30, 50, 30),
      reps("cross-climbers", 3, 30, 40, 30),
      reps("forward-lunge-twist", 3, 10, 20, 30),
      reps("gorilla-crawl", 3, 16, 26, 30),
      reps("plank-party", 3, 10, 20, 30),
      reps("plank-to-squat", 3, 15, 25, 30),
    ],
  },
];

export function discoverWorkoutIdeas(filters: {
  goal?: WorkoutGoal | "all";
  maxMinutes?: number;
  equipment?: string | "all";
} = {}) {
  return workoutIdeas.filter((idea) => {
    if (filters.goal && filters.goal !== "all" && idea.goal !== filters.goal) return false;
    if (filters.maxMinutes && idea.durationMinutes > filters.maxMinutes) return false;
    if (filters.equipment && filters.equipment !== "all" && !idea.equipment.includes(filters.equipment)) return false;
    return true;
  });
}

export function getWorkoutIdea(slug?: string) {
  return workoutIdeas.find((idea) => idea.slug === slug);
}
