"use client";

import { useActionState, useState } from "react";
import { Search, Plus, Star } from "lucide-react";
import { addGroceryItemAction, addMealEntryAction, addPlanItemAction, createCustomFoodAction, toggleFoodFavouriteAction } from "@/features/nutrition/actions";
import type { AuthActionState } from "@/features/auth/types";
import type { CatalogueRecipe } from "@/features/nutrition/catalogue";
import type { Locale } from "@/lib/i18n/config";
import { ActionFeedback } from "@/features/motion/action-feedback";

const initial: AuthActionState = { status: "idle" };
type FoodResult = { id: string; name: string; brand: string | null; servingGrams: number; energyKcal: number; proteinG: number; carbohydrateG: number; fatG: number; fibreG: number; isFavourite?: boolean };
const formText = { en: { searching: "Searching…", meal: "Meal", name: "Name", serving: "Serving (g)", saveFood: "Save custom food", saving: "Saving…", manual: "Manual meal", add: "Add", item: "Add item", quantity: "Quantity", unit: "Unit", category: "Category", favourite: "Favourite", yourFoods: "Your foods" }, mk: { searching: "Се пребарува…", meal: "Оброк", name: "Име", serving: "Порција (g)", saveFood: "Зачувај храна", saving: "Се зачувува…", manual: "Рачен оброк", add: "Додај", item: "Додај ставка", quantity: "Количина", unit: "Единица", category: "Категорија", favourite: "Омилено", yourFoods: "Ваша храна" } } as const;

function Status({ state }: { state: AuthActionState }) { return state.message ? <ActionFeedback className="form-status" status={state.status} message={state.message} /> : null; }

export function FoodSearchForm({ date, labels, locale, savedFoods = [] }: { date: string; labels: { search: string; add: string; source: string }; locale: Locale; savedFoods?: FoodResult[] }) {
  const t = formText[locale]; const [query, setQuery] = useState(""); const [results, setResults] = useState<FoodResult[]>(savedFoods); const [notice, setNotice] = useState(savedFoods.length ? t.yourFoods : ""); const [loading, setLoading] = useState(false); const [state, action, pending] = useActionState(addMealEntryAction, initial);
  async function search(event: React.FormEvent) { event.preventDefault(); if (query.trim().length < 2) return; setLoading(true); const response = await fetch(`/api/foods/search?q=${encodeURIComponent(query)}`); const data = await response.json(); setResults(data.results ?? []); setNotice(data.attribution ?? data.message ?? ""); setLoading(false); }
  return <div className="food-search-panel">
    <form className="food-search-row" onSubmit={search}><label className="sr-only" htmlFor="food-query">{labels.search}</label><input id="food-query" value={query} onChange={(event) => setQuery(event.target.value)} placeholder={locale === "mk" ? "Овес, леќа, јогурт…" : "Oats, lentils, yoghurt…"} minLength={2} /><button className="ui-button ui-button-secondary" disabled={loading}><Search aria-hidden="true" />{loading ? t.searching : labels.search}</button></form>
    {notice && <p className="source-note">{notice}</p>}
    <div className="food-results">{results.map((food) => <form action={action} className="food-result" key={food.id}>
      <div><strong>{food.name}</strong><span>{food.brand || `${Math.round(food.energyKcal)} kcal · ${food.proteinG} g protein / 100 g`}</span></div>
      {Object.entries({ foodId: /^[0-9a-f-]{36}$/i.test(food.id) ? food.id : "", foodName: food.name, energyKcal: food.energyKcal, proteinG: food.proteinG, carbohydrateG: food.carbohydrateG, fatG: food.fatG, fibreG: food.fibreG, loggedOn: date, id: food.id, saved: String(Boolean(food.isFavourite)) }).map(([name, value]) => <input key={name} type="hidden" name={name} value={value} />)}
      <label><span>{t.meal}</span><select name="mealSlot" defaultValue="breakfast"><option value="breakfast">{locale === "mk" ? "Појадок" : "Breakfast"}</option><option value="lunch">{locale === "mk" ? "Ручек" : "Lunch"}</option><option value="dinner">{locale === "mk" ? "Вечера" : "Dinner"}</option><option value="snack">{locale === "mk" ? "Ужина" : "Snack"}</option></select></label>
      <label><span>g</span><input name="amountGrams" type="number" min="1" max="5000" defaultValue={Math.round(food.servingGrams || 100)} /></label>
      <div className="food-result-actions">{/^[0-9a-f-]{36}$/i.test(food.id) && <button className={`icon-action quiet ${food.isFavourite ? "is-favourite" : ""}`} formAction={toggleFoodFavouriteAction} aria-label={`${t.favourite}: ${food.name}`}><Star aria-hidden="true" /></button>}<button className="icon-action" aria-label={`${labels.add}: ${food.name}`} disabled={pending}><Plus aria-hidden="true" /></button></div>
    </form>)}</div><Status state={state} />
  </div>;
}

export function CustomFoodForm({ locale }: { locale: Locale }) { const t = formText[locale]; const [state, action, pending] = useActionState(createCustomFoodAction, initial); return <form action={action} className="compact-form nutrition-custom-form"><label>{t.name}<input name="name" required minLength={2} /></label><label>{t.serving}<input name="servingGrams" type="number" min="1" defaultValue="100" required /></label>{[["energyKcal","kcal"],["proteinG",locale === "mk" ? "Протеини g" : "Protein g"],["carbohydrateG",locale === "mk" ? "Јаглехидрати g" : "Carbs g"],["fatG",locale === "mk" ? "Масти g" : "Fat g"],["fibreG",locale === "mk" ? "Влакна g" : "Fibre g"]].map(([name,label]) => <label key={name}>{label}<input name={name} type="number" min="0" step="0.1" defaultValue="0" required /></label>)}<button className="ui-button ui-button-primary" disabled={pending}>{pending ? t.saving : t.saveFood}</button><Status state={state} /></form>; }

export function PlanItemForm({ date, recipes, locale, compact = false, defaultRecipeSlug = "" }: { date: string; recipes: readonly CatalogueRecipe[]; locale: Locale; compact?: boolean; defaultRecipeSlug?: string }) { const t = formText[locale]; const [state, action, pending] = useActionState(addPlanItemAction, initial); const [recipeSlug, setRecipeSlug] = useState(defaultRecipeSlug); const selected = recipes.find((recipe) => recipe.slug === recipeSlug); return <form action={action} className={compact ? "planner-add-form compact" : "planner-add-form"}><input type="hidden" name="plannedOn" value={date} /><input type="hidden" name="recipeId" value={selected?.databaseReady ? selected.id : ""} /><label>{t.meal}<select name="mealSlot" defaultValue={selected?.meal ?? "breakfast"}><option value="breakfast">{locale === "mk" ? "Појадок" : "Breakfast"}</option><option value="lunch">{locale === "mk" ? "Ручек" : "Lunch"}</option><option value="dinner">{locale === "mk" ? "Вечера" : "Dinner"}</option><option value="snack">{locale === "mk" ? "Ужина" : "Snack"}</option></select></label><label>{locale === "mk" ? "Рецепт" : "Recipe"}<select value={recipeSlug} onChange={(e) => setRecipeSlug(e.target.value)}><option value="">{t.manual}</option>{recipes.map((recipe) => <option key={recipe.id} value={recipe.slug}>{recipe.title[locale]}</option>)}</select></label><label>{locale === "mk" ? "Име на оброк" : "Meal name"}<input name="label" defaultValue={selected?.title[locale] ?? ""} key={selected?.id ?? "manual"} required /></label><label>{locale === "mk" ? "Порции" : "Servings"}<input name="servings" type="number" min="0.5" step="0.5" defaultValue="1" /></label><button className="ui-button ui-button-primary" disabled={pending}>{t.add}</button><Status state={state} /></form>; }

export function GroceryItemForm({ locale }: { locale: Locale }) { const t = formText[locale]; const [state, action, pending] = useActionState(addGroceryItemAction, initial); return <form action={action} className="grocery-add-form"><label>{t.name}<input name="name" required /></label><label>{t.quantity}<input name="quantity" type="number" min="0.01" step="0.01" /></label><label>{t.unit}<input name="unit" placeholder="g, piece…" /></label><label>{t.category}<select name="category"><option>{locale === "mk" ? "Зеленчук и овошје" : "Produce"}</option><option>{locale === "mk" ? "Протеини" : "Protein"}</option><option>{locale === "mk" ? "Остава" : "Pantry"}</option><option>{locale === "mk" ? "Ладилник" : "Chilled"}</option><option>{locale === "mk" ? "Друго" : "Other"}</option></select></label><button className="ui-button ui-button-primary" disabled={pending}>{t.item}</button><Status state={state} /></form>; }
