import Link from "next/link";
import { ShoppingBasket, Trash2 } from "lucide-react";
import { deletePlanItemAction, generateGroceryListAction } from "@/features/nutrition/actions";
import { recipes } from "@/features/nutrition/catalogue";
import { getNutritionContent } from "@/features/nutrition/content";
import { weekDates } from "@/features/nutrition/domain";
import { PlanItemForm } from "@/features/nutrition/nutrition-forms";
import { loadMealPlan } from "@/features/nutrition/repository";
import { requireUser } from "@/features/auth/session";
import { getLocale } from "@/lib/i18n/server";

export default async function MealPlannerPage({ searchParams }: { searchParams: Promise<{ recipe?: string }> }) { const user = await requireUser(); const locale = await getLocale(); const c = getNutritionContent(locale); const today = new Date().toISOString().slice(0, 10); const dates = weekDates(today); const items = await loadMealPlan(user.id, dates[0], dates[6]); const query = await searchParams; const requested = recipes.find((recipe) => recipe.slug === query.recipe); return <main className="product-page"><header className="product-page-heading"><div><p className="eyebrow">{locale === "mk" ? "Обликувајте ја неделата" : "Shape the week"}</p><h1>{c.planner.title}</h1><p>{c.planner.intro}</p></div><form action={generateGroceryListAction}><button className="ui-button ui-button-secondary"><ShoppingBasket />{c.planner.generate}</button></form></header><section className="planner-week" aria-label={locale === "mk" ? "Тековна недела" : "Current week"}>{dates.map((date) => { const dayItems = items.filter((item) => item.planned_on === date); return <article className={`planner-day ${date === today ? "is-today" : ""}`} key={date}><header><time dateTime={date}><span>{new Intl.DateTimeFormat(locale === "mk" ? "mk-MK" : "en", { weekday: "short", timeZone: "UTC" }).format(new Date(`${date}T12:00:00Z`))}</span><strong>{new Intl.DateTimeFormat(locale === "mk" ? "mk-MK" : "en", { month: "short", day: "numeric", timeZone: "UTC" }).format(new Date(`${date}T12:00:00Z`))}</strong></time>{date === today && <i>{locale === "mk" ? "Денес" : "Today"}</i>}</header><div className="planner-day-items">{dayItems.length ? dayItems.map((item) => <div className="planner-item" key={item.id}><span>{c.common[item.meal_slot]}</span><strong>{item.label}</strong><small>{Number(item.servings)} {c.common.servings.toLowerCase()}</small><form action={deletePlanItemAction}><input type="hidden" name="id" value={item.id} /><button className="icon-action quiet" aria-label={locale === "mk" ? `Отстрани ${item.label}` : `Remove ${item.label}`}><Trash2 /></button></form></div>) : <p>{c.planner.empty}</p>}</div><details open={date === today && Boolean(requested)}><summary>{c.planner.add}</summary><PlanItemForm compact date={date} recipes={recipes} locale={locale} defaultRecipeSlug={date === today ? requested?.slug : undefined} /></details></article>; })}</section><div className="planner-footer"><Link href="/recipes">{locale === "mk" ? "Прегледај идеи за рецепти" : "Browse recipe ideas"}</Link><Link href="/grocery-list">{locale === "mk" ? "Прегледај список" : "Review grocery list"}</Link></div></main>; }
