import Link from "next/link";
import { ChevronLeft, ChevronRight, Trash2 } from "lucide-react";
import { deleteMealEntryAction } from "@/features/nutrition/actions";
import { buildNutritionTotals } from "@/features/nutrition/domain";
import { getNutritionContent } from "@/features/nutrition/content";
import { CustomFoodForm } from "@/features/nutrition/nutrition-forms";
import { FoodDiscovery } from "@/features/nutrition/food-discovery";
import { loadNutritionDay } from "@/features/nutrition/repository";
import { requireUser } from "@/features/auth/session";
import { getLocale } from "@/lib/i18n/server";

const slots = ["breakfast", "lunch", "dinner", "snack"] as const;
function moveDate(value: string, days: number) { const date = new Date(`${value}T12:00:00Z`); date.setUTCDate(date.getUTCDate() + days); return date.toISOString().slice(0, 10); }

export default async function NutritionPage({ searchParams }: { searchParams: Promise<{ date?: string }> }) {
  const user = await requireUser(); const locale = await getLocale(); const c = getNutritionContent(locale); const params = await searchParams; const today = new Date().toISOString().slice(0, 10); const date = /^\d{4}-\d{2}-\d{2}$/.test(params.date ?? "") ? params.date! : today; const data = await loadNutritionDay(user.id, date);
  const totals = buildNutritionTotals(data.entries.map((entry) => ({ energyKcal: Number(entry.energy_kcal), proteinG: Number(entry.protein_g), carbohydrateG: Number(entry.carbohydrate_g), fatG: Number(entry.fat_g), fibreG: Number(entry.fibre_g) })));
  const metrics = [{ label: c.nutrition.energy, value: totals.energyKcal, target: data.target?.energy_kcal, unit: "kcal", tone: "energy" }, { label: c.nutrition.protein, value: totals.proteinG, target: data.target?.protein_g, unit: "g", tone: "protein" }, { label: c.nutrition.carbs, value: totals.carbohydrateG, target: data.target?.carbohydrate_g, unit: "g", tone: "carbs" }, { label: c.nutrition.fat, value: totals.fatG, target: data.target?.fat_g, unit: "g", tone: "fat" }];
  return <main className="product-page nutrition-page"><header className="product-page-heading"><div><p className="eyebrow">Fuel with context</p><h1>{c.nutrition.title}</h1><p>{c.nutrition.intro}</p></div><nav className="date-stepper" aria-label="Nutrition date"><Link href={`/nutrition?date=${moveDate(date,-1)}`} aria-label="Previous day"><ChevronLeft /></Link><time dateTime={date}>{new Intl.DateTimeFormat(locale, { weekday: "short", month: "short", day: "numeric", timeZone: "UTC" }).format(new Date(`${date}T12:00:00Z`))}</time><Link href={`/nutrition?date=${moveDate(date,1)}`} aria-label="Next day"><ChevronRight /></Link></nav></header>
    <section className="nutrition-summary" aria-labelledby="daily-direction"><div className="nutrition-summary-heading"><div><span>{c.nutrition.targets}</span><strong>{Math.round(totals.energyKcal)} kcal logged</strong></div><Link href="/meal-planner">Plan the week</Link></div><div className="macro-grid">{metrics.map((metric) => { const target = metric.target ? Number(metric.target) : null; const ratio = target ? Math.min(100, metric.value / target * 100) : 0; return <div className={`macro-stat ${metric.tone}`} key={metric.label}><span>{metric.label}</span><strong>{Math.round(metric.value)} <small>{metric.unit}</small></strong><div className="metric-track"><i style={{ width: `${ratio}%` }} /></div><small>{target ? `${Math.max(0, Math.round(target - metric.value))} ${metric.unit} remaining` : c.nutrition.targetMissing}</small></div>; })}</div></section>
    <div className="nutrition-layout"><section className="meal-log"><div className="section-heading"><div><p className="eyebrow">Daily record</p><h2>Your meals</h2></div><span>{data.entries.length} items</span></div>{data.unavailable && <div className="inline-notice warning">Nutrition storage is not available yet. Apply the Phase 5 migration to enable logging.</div>}{slots.map((slot) => { const entries = data.entries.filter((entry) => entry.meal_slot === slot); return <article className="meal-section" key={slot}><header><h3>{c.common[slot]}</h3><strong>{Math.round(entries.reduce((sum, entry) => sum + Number(entry.energy_kcal), 0))} kcal</strong></header>{entries.length ? <ul>{entries.map((entry) => <li key={entry.id}><div><strong>{entry.food_name}</strong><span>{Number(entry.amount_grams)} g · {Number(entry.protein_g)} g protein</span></div><div><b>{Math.round(Number(entry.energy_kcal))} kcal</b><form action={deleteMealEntryAction}><input type="hidden" name="id" value={entry.id} /><button className="icon-action quiet" aria-label={`Remove ${entry.food_name}`}><Trash2 /></button></form></div></li>)}</ul> : <p className="empty-copy">{c.nutrition.noEntries}</p>}</article>; })}</section>
      <aside className="nutrition-tools"><section className="product-panel"><div className="section-heading"><div><p className="eyebrow">{locale === "mk" ? "Најдете и внесете" : "Find and log"}</p><h2>{c.nutrition.add}</h2></div></div><FoodDiscovery date={date} savedFoods={data.customFoods.map((food) => ({ id: food.id, name: food.name, brand: food.brand, servingGrams: Number(food.serving_grams), energyKcal: Number(food.energy_kcal), proteinG: Number(food.protein_g), carbohydrateG: Number(food.carbohydrate_g), fatG: Number(food.fat_g), fibreG: Number(food.fibre_g) }))} /></section><details className="product-panel custom-food-panel"><summary>{c.nutrition.custom}</summary><p>{locale === "mk" ? "Внесете ги вредностите од етикетата за 100 g." : "Enter values shown on the label per 100 g."}</p><CustomFoodForm locale={locale} /></details><nav className="nutrition-shortcuts"><Link href="/recipes">{locale === "mk" ? "Прегледај рецепти" : "Browse recipes"}</Link><Link href="/grocery-list">{locale === "mk" ? "Отвори намирници" : "Open groceries"}</Link></nav></aside></div></main>;
}
