import { Check, RotateCcw, ShoppingBasket, Trash2 } from "lucide-react";
import { deleteGroceryItemAction, generateGroceryListAction, toggleGroceryItemAction } from "@/features/nutrition/actions";
import { getNutritionContent } from "@/features/nutrition/content";
import { GroceryItemForm } from "@/features/nutrition/nutrition-forms";
import { loadGroceryItems } from "@/features/nutrition/repository";
import { requireUser } from "@/features/auth/session";
import { getLocale } from "@/lib/i18n/server";

export default async function GroceryListPage() { const user = await requireUser(); const locale = await getLocale(); const c = getNutritionContent(locale); const items = await loadGroceryItems(user.id); const groups = Object.entries(Object.groupBy(items, (item) => item.category)); const completed = items.filter((item) => item.is_checked).length; return <main className="product-page grocery-page"><header className="product-page-heading"><div><p className="eyebrow">{locale === "mk" ? "Купувајте според планот" : "Shop from the plan"}</p><h1>{c.groceries.title}</h1><p>{c.groceries.intro}</p></div><div className="grocery-progress"><strong>{completed} / {items.length}</strong><span>{locale === "mk" ? "означени" : "checked"}</span></div></header><div className="grocery-layout"><section className="grocery-list-panel"><form action={generateGroceryListAction} className="generate-list-action"><div><ShoppingBasket /><span><strong>{c.groceries.generate}</strong><small>{locale === "mk" ? "Точните единици остануваат одделни за списокот да биде веродостоен." : "Exact ingredient units stay separate so the list remains trustworthy."}</small></span></div><button className="ui-button ui-button-secondary">{locale === "mk" ? "Создај" : "Generate"}</button></form>{items.length ? groups.map(([category, rows]) => <section className="grocery-group" key={category}><h2>{category}</h2><ul>{(rows ?? []).map((item) => <li className={item.is_checked ? "is-checked" : ""} key={item.id}><form action={toggleGroceryItemAction}><input type="hidden" name="id" value={item.id} /><input type="hidden" name="checked" value={String(item.is_checked)} /><button className="grocery-check" aria-label={`${item.is_checked ? "Uncheck" : "Check"} ${item.name}`}>{item.is_checked ? <Check /> : null}</button></form><div><strong>{item.name}</strong><span>{item.quantity ? `${Number(item.quantity)} ${item.unit ?? ""}` : locale === "mk" ? "Без количина" : "No quantity"} · {item.source === "meal_plan" ? c.planner.title : locale === "mk" ? "Рачно" : "Manual"}</span></div><form action={deleteGroceryItemAction}><input type="hidden" name="id" value={item.id} /><button className="icon-action quiet" aria-label={`Remove ${item.name}`}><Trash2 /></button></form></li>)}</ul></section>) : <div className="empty-state"><ShoppingBasket /><h2>{locale === "mk" ? "Почнете со потребното" : "Start with what you need"}</h2><p>{c.groceries.empty}</p></div>}</section><aside className="product-panel grocery-add-panel"><div className="section-heading"><div><p className="eyebrow">{locale === "mk" ? "Рачна ставка" : "Manual item"}</p><h2>{c.groceries.add}</h2></div><RotateCcw aria-hidden="true" /></div><GroceryItemForm locale={locale} /></aside></div></main>; }
